[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "lattica-fhe-core-deep"
version = "0.1.1"
description = "Lattica FHE Core Python Bindings with Deep Binding"
authors = [
    "LatticaAI",
]
readme = "README.md"
packages = [
    { include = "lattica_fhe_core_deep" },
]
include = [
    { path = "lattica_fhe_core_deep/cpp_sdk_with_deep_binding.cpython*.so", format = "wheel" },
    { path = "lattica_fhe_core/libsodium.so.*", format = "wheel" },
]
exclude = [
    "dev_scripts/**/*",
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
