// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/context.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_serialization_2fcontext_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_serialization_2fcontext_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "global_params_and_state.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serialization_2fcontext_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serialization_2fcontext_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serialization_2fcontext_2eproto;
namespace lattica_proto {
class Context;
struct ContextDefaultTypeInternal;
extern ContextDefaultTypeInternal _Context_default_instance_;
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace lattica_proto {

// ===================================================================


// -------------------------------------------------------------------

class Context final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lattica_proto.Context) */ {
 public:
  inline Context() : Context(nullptr) {}
  ~Context() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Context(
      ::google::protobuf::internal::ConstantInitialized);

  inline Context(const Context& from) : Context(nullptr, from) {}
  inline Context(Context&& from) noexcept
      : Context(nullptr, std::move(from)) {}
  inline Context& operator=(const Context& from) {
    CopyFrom(from);
    return *this;
  }
  inline Context& operator=(Context&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Context& default_instance() {
    return *internal_default_instance();
  }
  static inline const Context* internal_default_instance() {
    return reinterpret_cast<const Context*>(
        &_Context_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Context& a, Context& b) { a.Swap(&b); }
  inline void Swap(Context* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Context* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Context* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Context>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Context& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Context& from) { Context::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Context* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "lattica_proto.Context"; }

 protected:
  explicit Context(::google::protobuf::Arena* arena);
  Context(::google::protobuf::Arena* arena, const Context& from);
  Context(::google::protobuf::Arena* arena, Context&& from) noexcept
      : Context(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParamsFieldNumber = 1,
    kInitStateFieldNumber = 2,
    kIsCkksFieldNumber = 4,
  };
  // .lattica_proto.Params params = 1;
  bool has_params() const;
  void clear_params() ;
  const ::lattica_proto::Params& params() const;
  PROTOBUF_NODISCARD ::lattica_proto::Params* release_params();
  ::lattica_proto::Params* mutable_params();
  void set_allocated_params(::lattica_proto::Params* value);
  void unsafe_arena_set_allocated_params(::lattica_proto::Params* value);
  ::lattica_proto::Params* unsafe_arena_release_params();

  private:
  const ::lattica_proto::Params& _internal_params() const;
  ::lattica_proto::Params* _internal_mutable_params();

  public:
  // .lattica_proto.State init_state = 2;
  bool has_init_state() const;
  void clear_init_state() ;
  const ::lattica_proto::State& init_state() const;
  PROTOBUF_NODISCARD ::lattica_proto::State* release_init_state();
  ::lattica_proto::State* mutable_init_state();
  void set_allocated_init_state(::lattica_proto::State* value);
  void unsafe_arena_set_allocated_init_state(::lattica_proto::State* value);
  ::lattica_proto::State* unsafe_arena_release_init_state();

  private:
  const ::lattica_proto::State& _internal_init_state() const;
  ::lattica_proto::State* _internal_mutable_init_state();

  public:
  // bool is_ckks = 4;
  void clear_is_ckks() ;
  bool is_ckks() const;
  void set_is_ckks(bool value);

  private:
  bool _internal_is_ckks() const;
  void _internal_set_is_ckks(bool value);

  public:
  // @@protoc_insertion_point(class_scope:lattica_proto.Context)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Context_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Context& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::lattica_proto::Params* params_;
    ::lattica_proto::State* init_state_;
    bool is_ckks_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_2fcontext_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Context

// .lattica_proto.Params params = 1;
inline bool Context::has_params() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.params_ != nullptr);
  return value;
}
inline const ::lattica_proto::Params& Context::_internal_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::Params* p = _impl_.params_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::Params&>(::lattica_proto::_Params_default_instance_);
}
inline const ::lattica_proto::Params& Context::params() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.Context.params)
  return _internal_params();
}
inline void Context::unsafe_arena_set_allocated_params(::lattica_proto::Params* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.params_);
  }
  _impl_.params_ = reinterpret_cast<::lattica_proto::Params*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.Context.params)
}
inline ::lattica_proto::Params* Context::release_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::Params* released = _impl_.params_;
  _impl_.params_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::Params* Context::unsafe_arena_release_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.Context.params)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::Params* temp = _impl_.params_;
  _impl_.params_ = nullptr;
  return temp;
}
inline ::lattica_proto::Params* Context::_internal_mutable_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.params_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::Params>(GetArena());
    _impl_.params_ = reinterpret_cast<::lattica_proto::Params*>(p);
  }
  return _impl_.params_;
}
inline ::lattica_proto::Params* Context::mutable_params() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::lattica_proto::Params* _msg = _internal_mutable_params();
  // @@protoc_insertion_point(field_mutable:lattica_proto.Context.params)
  return _msg;
}
inline void Context::set_allocated_params(::lattica_proto::Params* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.params_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.params_ = reinterpret_cast<::lattica_proto::Params*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.Context.params)
}

// .lattica_proto.State init_state = 2;
inline bool Context::has_init_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.init_state_ != nullptr);
  return value;
}
inline const ::lattica_proto::State& Context::_internal_init_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::State* p = _impl_.init_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::State&>(::lattica_proto::_State_default_instance_);
}
inline const ::lattica_proto::State& Context::init_state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.Context.init_state)
  return _internal_init_state();
}
inline void Context::unsafe_arena_set_allocated_init_state(::lattica_proto::State* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.init_state_);
  }
  _impl_.init_state_ = reinterpret_cast<::lattica_proto::State*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.Context.init_state)
}
inline ::lattica_proto::State* Context::release_init_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::State* released = _impl_.init_state_;
  _impl_.init_state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::State* Context::unsafe_arena_release_init_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.Context.init_state)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::State* temp = _impl_.init_state_;
  _impl_.init_state_ = nullptr;
  return temp;
}
inline ::lattica_proto::State* Context::_internal_mutable_init_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.init_state_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::State>(GetArena());
    _impl_.init_state_ = reinterpret_cast<::lattica_proto::State*>(p);
  }
  return _impl_.init_state_;
}
inline ::lattica_proto::State* Context::mutable_init_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::lattica_proto::State* _msg = _internal_mutable_init_state();
  // @@protoc_insertion_point(field_mutable:lattica_proto.Context.init_state)
  return _msg;
}
inline void Context::set_allocated_init_state(::lattica_proto::State* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.init_state_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.init_state_ = reinterpret_cast<::lattica_proto::State*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.Context.init_state)
}

// bool is_ckks = 4;
inline void Context::clear_is_ckks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_ckks_ = false;
}
inline bool Context::is_ckks() const {
  // @@protoc_insertion_point(field_get:lattica_proto.Context.is_ckks)
  return _internal_is_ckks();
}
inline void Context::set_is_ckks(bool value) {
  _internal_set_is_ckks(value);
  // @@protoc_insertion_point(field_set:lattica_proto.Context.is_ckks)
}
inline bool Context::_internal_is_ckks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_ckks_;
}
inline void Context::_internal_set_is_ckks(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_ckks_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_serialization_2fcontext_2eproto_2epb_2eh
