// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/crt_params_and_state.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_serialization_2fcrt_5fparams_5fand_5fstate_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_serialization_2fcrt_5fparams_5fand_5fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "generic.pb.h"
#include "mod_params_and_state.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serialization_2fcrt_5fparams_5fand_5fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serialization_2fcrt_5fparams_5fand_5fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serialization_2fcrt_5fparams_5fand_5fstate_2eproto;
namespace lattica_proto {
class CrtParams;
struct CrtParamsDefaultTypeInternal;
extern CrtParamsDefaultTypeInternal _CrtParams_default_instance_;
class CrtState;
struct CrtStateDefaultTypeInternal;
extern CrtStateDefaultTypeInternal _CrtState_default_instance_;
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace lattica_proto {

// ===================================================================


// -------------------------------------------------------------------

class CrtParams final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lattica_proto.CrtParams) */ {
 public:
  inline CrtParams() : CrtParams(nullptr) {}
  ~CrtParams() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CrtParams(
      ::google::protobuf::internal::ConstantInitialized);

  inline CrtParams(const CrtParams& from) : CrtParams(nullptr, from) {}
  inline CrtParams(CrtParams&& from) noexcept
      : CrtParams(nullptr, std::move(from)) {}
  inline CrtParams& operator=(const CrtParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline CrtParams& operator=(CrtParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CrtParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const CrtParams* internal_default_instance() {
    return reinterpret_cast<const CrtParams*>(
        &_CrtParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CrtParams& a, CrtParams& b) { a.Swap(&b); }
  inline void Swap(CrtParams* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CrtParams* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CrtParams* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<CrtParams>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CrtParams& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CrtParams& from) { CrtParams::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CrtParams* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "lattica_proto.CrtParams"; }

 protected:
  explicit CrtParams(::google::protobuf::Arena* arena);
  CrtParams(::google::protobuf::Arena* arena, const CrtParams& from);
  CrtParams(::google::protobuf::Arena* arena, CrtParams&& from) noexcept
      : CrtParams(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPermFieldNumber = 4,
    kPermPairsFieldNumber = 5,
    kMFieldNumber = 1,
    kNFieldNumber = 2,
    kLognFieldNumber = 3,
  };
  // .lattica_proto.TensorHolder perm = 4;
  bool has_perm() const;
  void clear_perm() ;
  const ::lattica_proto::TensorHolder& perm() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_perm();
  ::lattica_proto::TensorHolder* mutable_perm();
  void set_allocated_perm(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_perm(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_perm();

  private:
  const ::lattica_proto::TensorHolder& _internal_perm() const;
  ::lattica_proto::TensorHolder* _internal_mutable_perm();

  public:
  // .lattica_proto.TensorHolder perm_pairs = 5;
  bool has_perm_pairs() const;
  void clear_perm_pairs() ;
  const ::lattica_proto::TensorHolder& perm_pairs() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_perm_pairs();
  ::lattica_proto::TensorHolder* mutable_perm_pairs();
  void set_allocated_perm_pairs(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_perm_pairs(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_perm_pairs();

  private:
  const ::lattica_proto::TensorHolder& _internal_perm_pairs() const;
  ::lattica_proto::TensorHolder* _internal_mutable_perm_pairs();

  public:
  // int32 m = 1;
  void clear_m() ;
  ::int32_t m() const;
  void set_m(::int32_t value);

  private:
  ::int32_t _internal_m() const;
  void _internal_set_m(::int32_t value);

  public:
  // int32 n = 2;
  void clear_n() ;
  ::int32_t n() const;
  void set_n(::int32_t value);

  private:
  ::int32_t _internal_n() const;
  void _internal_set_n(::int32_t value);

  public:
  // int32 logn = 3;
  void clear_logn() ;
  ::int32_t logn() const;
  void set_logn(::int32_t value);

  private:
  ::int32_t _internal_logn() const;
  void _internal_set_logn(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lattica_proto.CrtParams)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CrtParams_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CrtParams& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::lattica_proto::TensorHolder* perm_;
    ::lattica_proto::TensorHolder* perm_pairs_;
    ::int32_t m_;
    ::int32_t n_;
    ::int32_t logn_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_2fcrt_5fparams_5fand_5fstate_2eproto;
};
// -------------------------------------------------------------------

class CrtState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lattica_proto.CrtState) */ {
 public:
  inline CrtState() : CrtState(nullptr) {}
  ~CrtState() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CrtState(
      ::google::protobuf::internal::ConstantInitialized);

  inline CrtState(const CrtState& from) : CrtState(nullptr, from) {}
  inline CrtState(CrtState&& from) noexcept
      : CrtState(nullptr, std::move(from)) {}
  inline CrtState& operator=(const CrtState& from) {
    CopyFrom(from);
    return *this;
  }
  inline CrtState& operator=(CrtState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CrtState& default_instance() {
    return *internal_default_instance();
  }
  static inline const CrtState* internal_default_instance() {
    return reinterpret_cast<const CrtState*>(
        &_CrtState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CrtState& a, CrtState& b) { a.Swap(&b); }
  inline void Swap(CrtState* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CrtState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CrtState* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<CrtState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CrtState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CrtState& from) { CrtState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CrtState* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "lattica_proto.CrtState"; }

 protected:
  explicit CrtState(::google::protobuf::Arena* arena);
  CrtState(::google::protobuf::Arena* arena, const CrtState& from);
  CrtState(::google::protobuf::Arena* arena, CrtState&& from) noexcept
      : CrtState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModStateFieldNumber = 1,
    kActivePsiArrFieldNumber = 2,
    kActivePsiInvArrFieldNumber = 3,
    kActiveNInvListFieldNumber = 4,
  };
  // .lattica_proto.ModState mod_state = 1;
  bool has_mod_state() const;
  void clear_mod_state() ;
  const ::lattica_proto::ModState& mod_state() const;
  PROTOBUF_NODISCARD ::lattica_proto::ModState* release_mod_state();
  ::lattica_proto::ModState* mutable_mod_state();
  void set_allocated_mod_state(::lattica_proto::ModState* value);
  void unsafe_arena_set_allocated_mod_state(::lattica_proto::ModState* value);
  ::lattica_proto::ModState* unsafe_arena_release_mod_state();

  private:
  const ::lattica_proto::ModState& _internal_mod_state() const;
  ::lattica_proto::ModState* _internal_mutable_mod_state();

  public:
  // .lattica_proto.TensorHolder active_psi_arr = 2;
  bool has_active_psi_arr() const;
  void clear_active_psi_arr() ;
  const ::lattica_proto::TensorHolder& active_psi_arr() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_psi_arr();
  ::lattica_proto::TensorHolder* mutable_active_psi_arr();
  void set_allocated_active_psi_arr(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_psi_arr(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_psi_arr();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_psi_arr() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_psi_arr();

  public:
  // .lattica_proto.TensorHolder active_psi_inv_arr = 3;
  bool has_active_psi_inv_arr() const;
  void clear_active_psi_inv_arr() ;
  const ::lattica_proto::TensorHolder& active_psi_inv_arr() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_psi_inv_arr();
  ::lattica_proto::TensorHolder* mutable_active_psi_inv_arr();
  void set_allocated_active_psi_inv_arr(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_psi_inv_arr(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_psi_inv_arr();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_psi_inv_arr() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_psi_inv_arr();

  public:
  // .lattica_proto.TensorHolder active_n_inv_list = 4;
  bool has_active_n_inv_list() const;
  void clear_active_n_inv_list() ;
  const ::lattica_proto::TensorHolder& active_n_inv_list() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_n_inv_list();
  ::lattica_proto::TensorHolder* mutable_active_n_inv_list();
  void set_allocated_active_n_inv_list(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_n_inv_list(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_n_inv_list();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_n_inv_list() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_n_inv_list();

  public:
  // @@protoc_insertion_point(class_scope:lattica_proto.CrtState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 4,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CrtState_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CrtState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::lattica_proto::ModState* mod_state_;
    ::lattica_proto::TensorHolder* active_psi_arr_;
    ::lattica_proto::TensorHolder* active_psi_inv_arr_;
    ::lattica_proto::TensorHolder* active_n_inv_list_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_2fcrt_5fparams_5fand_5fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CrtState

// .lattica_proto.ModState mod_state = 1;
inline bool CrtState::has_mod_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.mod_state_ != nullptr);
  return value;
}
inline const ::lattica_proto::ModState& CrtState::_internal_mod_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::ModState* p = _impl_.mod_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::ModState&>(::lattica_proto::_ModState_default_instance_);
}
inline const ::lattica_proto::ModState& CrtState::mod_state() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtState.mod_state)
  return _internal_mod_state();
}
inline void CrtState::unsafe_arena_set_allocated_mod_state(::lattica_proto::ModState* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.mod_state_);
  }
  _impl_.mod_state_ = reinterpret_cast<::lattica_proto::ModState*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtState.mod_state)
}
inline ::lattica_proto::ModState* CrtState::release_mod_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::ModState* released = _impl_.mod_state_;
  _impl_.mod_state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::ModState* CrtState::unsafe_arena_release_mod_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtState.mod_state)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::ModState* temp = _impl_.mod_state_;
  _impl_.mod_state_ = nullptr;
  return temp;
}
inline ::lattica_proto::ModState* CrtState::_internal_mutable_mod_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.mod_state_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::ModState>(GetArena());
    _impl_.mod_state_ = reinterpret_cast<::lattica_proto::ModState*>(p);
  }
  return _impl_.mod_state_;
}
inline ::lattica_proto::ModState* CrtState::mutable_mod_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::lattica_proto::ModState* _msg = _internal_mutable_mod_state();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtState.mod_state)
  return _msg;
}
inline void CrtState::set_allocated_mod_state(::lattica_proto::ModState* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.mod_state_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.mod_state_ = reinterpret_cast<::lattica_proto::ModState*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtState.mod_state)
}

// .lattica_proto.TensorHolder active_psi_arr = 2;
inline bool CrtState::has_active_psi_arr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_psi_arr_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& CrtState::_internal_active_psi_arr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_psi_arr_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& CrtState::active_psi_arr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtState.active_psi_arr)
  return _internal_active_psi_arr();
}
inline void CrtState::unsafe_arena_set_allocated_active_psi_arr(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_psi_arr_);
  }
  _impl_.active_psi_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtState.active_psi_arr)
}
inline ::lattica_proto::TensorHolder* CrtState::release_active_psi_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* released = _impl_.active_psi_arr_;
  _impl_.active_psi_arr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* CrtState::unsafe_arena_release_active_psi_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtState.active_psi_arr)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_psi_arr_;
  _impl_.active_psi_arr_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* CrtState::_internal_mutable_active_psi_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_psi_arr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_psi_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_psi_arr_;
}
inline ::lattica_proto::TensorHolder* CrtState::mutable_active_psi_arr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_psi_arr();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtState.active_psi_arr)
  return _msg;
}
inline void CrtState::set_allocated_active_psi_arr(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_psi_arr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.active_psi_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtState.active_psi_arr)
}

// .lattica_proto.TensorHolder active_psi_inv_arr = 3;
inline bool CrtState::has_active_psi_inv_arr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_psi_inv_arr_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& CrtState::_internal_active_psi_inv_arr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_psi_inv_arr_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& CrtState::active_psi_inv_arr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtState.active_psi_inv_arr)
  return _internal_active_psi_inv_arr();
}
inline void CrtState::unsafe_arena_set_allocated_active_psi_inv_arr(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_psi_inv_arr_);
  }
  _impl_.active_psi_inv_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtState.active_psi_inv_arr)
}
inline ::lattica_proto::TensorHolder* CrtState::release_active_psi_inv_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::lattica_proto::TensorHolder* released = _impl_.active_psi_inv_arr_;
  _impl_.active_psi_inv_arr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* CrtState::unsafe_arena_release_active_psi_inv_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtState.active_psi_inv_arr)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_psi_inv_arr_;
  _impl_.active_psi_inv_arr_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* CrtState::_internal_mutable_active_psi_inv_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_psi_inv_arr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_psi_inv_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_psi_inv_arr_;
}
inline ::lattica_proto::TensorHolder* CrtState::mutable_active_psi_inv_arr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_psi_inv_arr();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtState.active_psi_inv_arr)
  return _msg;
}
inline void CrtState::set_allocated_active_psi_inv_arr(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_psi_inv_arr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.active_psi_inv_arr_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtState.active_psi_inv_arr)
}

// .lattica_proto.TensorHolder active_n_inv_list = 4;
inline bool CrtState::has_active_n_inv_list() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_n_inv_list_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& CrtState::_internal_active_n_inv_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_n_inv_list_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& CrtState::active_n_inv_list() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtState.active_n_inv_list)
  return _internal_active_n_inv_list();
}
inline void CrtState::unsafe_arena_set_allocated_active_n_inv_list(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_n_inv_list_);
  }
  _impl_.active_n_inv_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtState.active_n_inv_list)
}
inline ::lattica_proto::TensorHolder* CrtState::release_active_n_inv_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::lattica_proto::TensorHolder* released = _impl_.active_n_inv_list_;
  _impl_.active_n_inv_list_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* CrtState::unsafe_arena_release_active_n_inv_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtState.active_n_inv_list)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_n_inv_list_;
  _impl_.active_n_inv_list_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* CrtState::_internal_mutable_active_n_inv_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_n_inv_list_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_n_inv_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_n_inv_list_;
}
inline ::lattica_proto::TensorHolder* CrtState::mutable_active_n_inv_list() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_n_inv_list();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtState.active_n_inv_list)
  return _msg;
}
inline void CrtState::set_allocated_active_n_inv_list(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_n_inv_list_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.active_n_inv_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtState.active_n_inv_list)
}

// -------------------------------------------------------------------

// CrtParams

// int32 m = 1;
inline void CrtParams::clear_m() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_ = 0;
}
inline ::int32_t CrtParams::m() const {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtParams.m)
  return _internal_m();
}
inline void CrtParams::set_m(::int32_t value) {
  _internal_set_m(value);
  // @@protoc_insertion_point(field_set:lattica_proto.CrtParams.m)
}
inline ::int32_t CrtParams::_internal_m() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_;
}
inline void CrtParams::_internal_set_m(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_ = value;
}

// int32 n = 2;
inline void CrtParams::clear_n() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_ = 0;
}
inline ::int32_t CrtParams::n() const {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtParams.n)
  return _internal_n();
}
inline void CrtParams::set_n(::int32_t value) {
  _internal_set_n(value);
  // @@protoc_insertion_point(field_set:lattica_proto.CrtParams.n)
}
inline ::int32_t CrtParams::_internal_n() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.n_;
}
inline void CrtParams::_internal_set_n(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_ = value;
}

// int32 logn = 3;
inline void CrtParams::clear_logn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logn_ = 0;
}
inline ::int32_t CrtParams::logn() const {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtParams.logn)
  return _internal_logn();
}
inline void CrtParams::set_logn(::int32_t value) {
  _internal_set_logn(value);
  // @@protoc_insertion_point(field_set:lattica_proto.CrtParams.logn)
}
inline ::int32_t CrtParams::_internal_logn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.logn_;
}
inline void CrtParams::_internal_set_logn(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logn_ = value;
}

// .lattica_proto.TensorHolder perm = 4;
inline bool CrtParams::has_perm() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.perm_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& CrtParams::_internal_perm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.perm_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& CrtParams::perm() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtParams.perm)
  return _internal_perm();
}
inline void CrtParams::unsafe_arena_set_allocated_perm(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.perm_);
  }
  _impl_.perm_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtParams.perm)
}
inline ::lattica_proto::TensorHolder* CrtParams::release_perm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::TensorHolder* released = _impl_.perm_;
  _impl_.perm_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* CrtParams::unsafe_arena_release_perm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtParams.perm)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::TensorHolder* temp = _impl_.perm_;
  _impl_.perm_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* CrtParams::_internal_mutable_perm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.perm_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.perm_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.perm_;
}
inline ::lattica_proto::TensorHolder* CrtParams::mutable_perm() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_perm();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtParams.perm)
  return _msg;
}
inline void CrtParams::set_allocated_perm(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.perm_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.perm_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtParams.perm)
}

// .lattica_proto.TensorHolder perm_pairs = 5;
inline bool CrtParams::has_perm_pairs() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.perm_pairs_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& CrtParams::_internal_perm_pairs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.perm_pairs_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& CrtParams::perm_pairs() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.CrtParams.perm_pairs)
  return _internal_perm_pairs();
}
inline void CrtParams::unsafe_arena_set_allocated_perm_pairs(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.perm_pairs_);
  }
  _impl_.perm_pairs_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.CrtParams.perm_pairs)
}
inline ::lattica_proto::TensorHolder* CrtParams::release_perm_pairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* released = _impl_.perm_pairs_;
  _impl_.perm_pairs_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* CrtParams::unsafe_arena_release_perm_pairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.CrtParams.perm_pairs)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* temp = _impl_.perm_pairs_;
  _impl_.perm_pairs_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* CrtParams::_internal_mutable_perm_pairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.perm_pairs_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.perm_pairs_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.perm_pairs_;
}
inline ::lattica_proto::TensorHolder* CrtParams::mutable_perm_pairs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_perm_pairs();
  // @@protoc_insertion_point(field_mutable:lattica_proto.CrtParams.perm_pairs)
  return _msg;
}
inline void CrtParams::set_allocated_perm_pairs(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.perm_pairs_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.perm_pairs_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.CrtParams.perm_pairs)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_serialization_2fcrt_5fparams_5fand_5fstate_2eproto_2epb_2eh
