// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/mod_params_and_state.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_serialization_2fmod_5fparams_5fand_5fstate_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_serialization_2fmod_5fparams_5fand_5fstate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "generic.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serialization_2fmod_5fparams_5fand_5fstate_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serialization_2fmod_5fparams_5fand_5fstate_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto;
namespace lattica_proto {
class ModState;
struct ModStateDefaultTypeInternal;
extern ModStateDefaultTypeInternal _ModState_default_instance_;
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace lattica_proto {

// ===================================================================


// -------------------------------------------------------------------

class ModState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lattica_proto.ModState) */ {
 public:
  inline ModState() : ModState(nullptr) {}
  ~ModState() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModState(
      ::google::protobuf::internal::ConstantInitialized);

  inline ModState(const ModState& from) : ModState(nullptr, from) {}
  inline ModState(ModState&& from) noexcept
      : ModState(nullptr, std::move(from)) {}
  inline ModState& operator=(const ModState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModState& operator=(ModState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModState& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModState* internal_default_instance() {
    return reinterpret_cast<const ModState*>(
        &_ModState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ModState& a, ModState& b) { a.Swap(&b); }
  inline void Swap(ModState* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModState* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ModState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModState& from) { ModState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ModState* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "lattica_proto.ModState"; }

 protected:
  explicit ModState(::google::protobuf::Arena* arena);
  ModState(::google::protobuf::Arena* arena, const ModState& from);
  ModState(::google::protobuf::Arena* arena, ModState&& from) noexcept
      : ModState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActiveReconstructionTermsFieldNumber = 6,
    kActiveQFieldNumber = 1,
    kActiveQListFieldNumber = 3,
    kActiveRowsFieldNumber = 4,
    kActiveColsFieldNumber = 5,
    kActiveLenQListFieldNumber = 2,
  };
  // repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
  int active_reconstruction_terms_size() const;
  private:
  int _internal_active_reconstruction_terms_size() const;

  public:
  void clear_active_reconstruction_terms() ;
  ::lattica_proto::BigInt* mutable_active_reconstruction_terms(int index);
  ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>* mutable_active_reconstruction_terms();

  private:
  const ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>& _internal_active_reconstruction_terms() const;
  ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>* _internal_mutable_active_reconstruction_terms();
  public:
  const ::lattica_proto::BigInt& active_reconstruction_terms(int index) const;
  ::lattica_proto::BigInt* add_active_reconstruction_terms();
  const ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>& active_reconstruction_terms() const;
  // .lattica_proto.BigInt active_q = 1;
  bool has_active_q() const;
  void clear_active_q() ;
  const ::lattica_proto::BigInt& active_q() const;
  PROTOBUF_NODISCARD ::lattica_proto::BigInt* release_active_q();
  ::lattica_proto::BigInt* mutable_active_q();
  void set_allocated_active_q(::lattica_proto::BigInt* value);
  void unsafe_arena_set_allocated_active_q(::lattica_proto::BigInt* value);
  ::lattica_proto::BigInt* unsafe_arena_release_active_q();

  private:
  const ::lattica_proto::BigInt& _internal_active_q() const;
  ::lattica_proto::BigInt* _internal_mutable_active_q();

  public:
  // .lattica_proto.TensorHolder active_q_list = 3;
  bool has_active_q_list() const;
  void clear_active_q_list() ;
  const ::lattica_proto::TensorHolder& active_q_list() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_q_list();
  ::lattica_proto::TensorHolder* mutable_active_q_list();
  void set_allocated_active_q_list(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_q_list(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_q_list();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_q_list() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_q_list();

  public:
  // .lattica_proto.TensorHolder active_rows = 4;
  bool has_active_rows() const;
  void clear_active_rows() ;
  const ::lattica_proto::TensorHolder& active_rows() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_rows();
  ::lattica_proto::TensorHolder* mutable_active_rows();
  void set_allocated_active_rows(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_rows(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_rows();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_rows() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_rows();

  public:
  // .lattica_proto.TensorHolder active_cols = 5;
  bool has_active_cols() const;
  void clear_active_cols() ;
  const ::lattica_proto::TensorHolder& active_cols() const;
  PROTOBUF_NODISCARD ::lattica_proto::TensorHolder* release_active_cols();
  ::lattica_proto::TensorHolder* mutable_active_cols();
  void set_allocated_active_cols(::lattica_proto::TensorHolder* value);
  void unsafe_arena_set_allocated_active_cols(::lattica_proto::TensorHolder* value);
  ::lattica_proto::TensorHolder* unsafe_arena_release_active_cols();

  private:
  const ::lattica_proto::TensorHolder& _internal_active_cols() const;
  ::lattica_proto::TensorHolder* _internal_mutable_active_cols();

  public:
  // int32 active_len_q_list = 2;
  void clear_active_len_q_list() ;
  ::int32_t active_len_q_list() const;
  void set_active_len_q_list(::int32_t value);

  private:
  ::int32_t _internal_active_len_q_list() const;
  void _internal_set_active_len_q_list(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lattica_proto.ModState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 5,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ModState_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ModState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::lattica_proto::BigInt > active_reconstruction_terms_;
    ::lattica_proto::BigInt* active_q_;
    ::lattica_proto::TensorHolder* active_q_list_;
    ::lattica_proto::TensorHolder* active_rows_;
    ::lattica_proto::TensorHolder* active_cols_;
    ::int32_t active_len_q_list_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_2fmod_5fparams_5fand_5fstate_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ModState

// .lattica_proto.BigInt active_q = 1;
inline bool ModState::has_active_q() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_q_ != nullptr);
  return value;
}
inline const ::lattica_proto::BigInt& ModState::_internal_active_q() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::BigInt* p = _impl_.active_q_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::BigInt&>(::lattica_proto::_BigInt_default_instance_);
}
inline const ::lattica_proto::BigInt& ModState::active_q() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_q)
  return _internal_active_q();
}
inline void ModState::unsafe_arena_set_allocated_active_q(::lattica_proto::BigInt* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_q_);
  }
  _impl_.active_q_ = reinterpret_cast<::lattica_proto::BigInt*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.ModState.active_q)
}
inline ::lattica_proto::BigInt* ModState::release_active_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::BigInt* released = _impl_.active_q_;
  _impl_.active_q_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::BigInt* ModState::unsafe_arena_release_active_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.ModState.active_q)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::lattica_proto::BigInt* temp = _impl_.active_q_;
  _impl_.active_q_ = nullptr;
  return temp;
}
inline ::lattica_proto::BigInt* ModState::_internal_mutable_active_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_q_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::BigInt>(GetArena());
    _impl_.active_q_ = reinterpret_cast<::lattica_proto::BigInt*>(p);
  }
  return _impl_.active_q_;
}
inline ::lattica_proto::BigInt* ModState::mutable_active_q() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::lattica_proto::BigInt* _msg = _internal_mutable_active_q();
  // @@protoc_insertion_point(field_mutable:lattica_proto.ModState.active_q)
  return _msg;
}
inline void ModState::set_allocated_active_q(::lattica_proto::BigInt* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_q_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.active_q_ = reinterpret_cast<::lattica_proto::BigInt*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.ModState.active_q)
}

// int32 active_len_q_list = 2;
inline void ModState::clear_active_len_q_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_len_q_list_ = 0;
}
inline ::int32_t ModState::active_len_q_list() const {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_len_q_list)
  return _internal_active_len_q_list();
}
inline void ModState::set_active_len_q_list(::int32_t value) {
  _internal_set_active_len_q_list(value);
  // @@protoc_insertion_point(field_set:lattica_proto.ModState.active_len_q_list)
}
inline ::int32_t ModState::_internal_active_len_q_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.active_len_q_list_;
}
inline void ModState::_internal_set_active_len_q_list(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_len_q_list_ = value;
}

// .lattica_proto.TensorHolder active_q_list = 3;
inline bool ModState::has_active_q_list() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_q_list_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& ModState::_internal_active_q_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_q_list_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& ModState::active_q_list() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_q_list)
  return _internal_active_q_list();
}
inline void ModState::unsafe_arena_set_allocated_active_q_list(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_q_list_);
  }
  _impl_.active_q_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.ModState.active_q_list)
}
inline ::lattica_proto::TensorHolder* ModState::release_active_q_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* released = _impl_.active_q_list_;
  _impl_.active_q_list_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* ModState::unsafe_arena_release_active_q_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.ModState.active_q_list)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_q_list_;
  _impl_.active_q_list_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* ModState::_internal_mutable_active_q_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_q_list_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_q_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_q_list_;
}
inline ::lattica_proto::TensorHolder* ModState::mutable_active_q_list() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_q_list();
  // @@protoc_insertion_point(field_mutable:lattica_proto.ModState.active_q_list)
  return _msg;
}
inline void ModState::set_allocated_active_q_list(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_q_list_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.active_q_list_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.ModState.active_q_list)
}

// .lattica_proto.TensorHolder active_rows = 4;
inline bool ModState::has_active_rows() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_rows_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& ModState::_internal_active_rows() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_rows_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& ModState::active_rows() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_rows)
  return _internal_active_rows();
}
inline void ModState::unsafe_arena_set_allocated_active_rows(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_rows_);
  }
  _impl_.active_rows_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.ModState.active_rows)
}
inline ::lattica_proto::TensorHolder* ModState::release_active_rows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::lattica_proto::TensorHolder* released = _impl_.active_rows_;
  _impl_.active_rows_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* ModState::unsafe_arena_release_active_rows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.ModState.active_rows)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_rows_;
  _impl_.active_rows_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* ModState::_internal_mutable_active_rows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_rows_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_rows_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_rows_;
}
inline ::lattica_proto::TensorHolder* ModState::mutable_active_rows() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_rows();
  // @@protoc_insertion_point(field_mutable:lattica_proto.ModState.active_rows)
  return _msg;
}
inline void ModState::set_allocated_active_rows(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_rows_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.active_rows_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.ModState.active_rows)
}

// .lattica_proto.TensorHolder active_cols = 5;
inline bool ModState::has_active_cols() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.active_cols_ != nullptr);
  return value;
}
inline const ::lattica_proto::TensorHolder& ModState::_internal_active_cols() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::lattica_proto::TensorHolder* p = _impl_.active_cols_;
  return p != nullptr ? *p : reinterpret_cast<const ::lattica_proto::TensorHolder&>(::lattica_proto::_TensorHolder_default_instance_);
}
inline const ::lattica_proto::TensorHolder& ModState::active_cols() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_cols)
  return _internal_active_cols();
}
inline void ModState::unsafe_arena_set_allocated_active_cols(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_cols_);
  }
  _impl_.active_cols_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lattica_proto.ModState.active_cols)
}
inline ::lattica_proto::TensorHolder* ModState::release_active_cols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::lattica_proto::TensorHolder* released = _impl_.active_cols_;
  _impl_.active_cols_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::lattica_proto::TensorHolder* ModState::unsafe_arena_release_active_cols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lattica_proto.ModState.active_cols)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::lattica_proto::TensorHolder* temp = _impl_.active_cols_;
  _impl_.active_cols_ = nullptr;
  return temp;
}
inline ::lattica_proto::TensorHolder* ModState::_internal_mutable_active_cols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_cols_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::lattica_proto::TensorHolder>(GetArena());
    _impl_.active_cols_ = reinterpret_cast<::lattica_proto::TensorHolder*>(p);
  }
  return _impl_.active_cols_;
}
inline ::lattica_proto::TensorHolder* ModState::mutable_active_cols() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::lattica_proto::TensorHolder* _msg = _internal_mutable_active_cols();
  // @@protoc_insertion_point(field_mutable:lattica_proto.ModState.active_cols)
  return _msg;
}
inline void ModState::set_allocated_active_cols(::lattica_proto::TensorHolder* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_cols_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.active_cols_ = reinterpret_cast<::lattica_proto::TensorHolder*>(value);
  // @@protoc_insertion_point(field_set_allocated:lattica_proto.ModState.active_cols)
}

// repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
inline int ModState::_internal_active_reconstruction_terms_size() const {
  return _internal_active_reconstruction_terms().size();
}
inline int ModState::active_reconstruction_terms_size() const {
  return _internal_active_reconstruction_terms_size();
}
inline ::lattica_proto::BigInt* ModState::mutable_active_reconstruction_terms(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:lattica_proto.ModState.active_reconstruction_terms)
  return _internal_mutable_active_reconstruction_terms()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>* ModState::mutable_active_reconstruction_terms()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:lattica_proto.ModState.active_reconstruction_terms)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_active_reconstruction_terms();
}
inline const ::lattica_proto::BigInt& ModState::active_reconstruction_terms(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lattica_proto.ModState.active_reconstruction_terms)
  return _internal_active_reconstruction_terms().Get(index);
}
inline ::lattica_proto::BigInt* ModState::add_active_reconstruction_terms() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::lattica_proto::BigInt* _add = _internal_mutable_active_reconstruction_terms()->Add();
  // @@protoc_insertion_point(field_add:lattica_proto.ModState.active_reconstruction_terms)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>& ModState::active_reconstruction_terms() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:lattica_proto.ModState.active_reconstruction_terms)
  return _internal_active_reconstruction_terms();
}
inline const ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>&
ModState::_internal_active_reconstruction_terms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.active_reconstruction_terms_;
}
inline ::google::protobuf::RepeatedPtrField<::lattica_proto::BigInt>*
ModState::_internal_mutable_active_reconstruction_terms() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.active_reconstruction_terms_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_serialization_2fmod_5fparams_5fand_5fstate_2eproto_2epb_2eh
