// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/pt_shape.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_serialization_2fpt_5fshape_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_serialization_2fpt_5fshape_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serialization_2fpt_5fshape_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serialization_2fpt_5fshape_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serialization_2fpt_5fshape_2eproto;
namespace lattica_proto {
class PtShape;
struct PtShapeDefaultTypeInternal;
extern PtShapeDefaultTypeInternal _PtShape_default_instance_;
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace lattica_proto {

// ===================================================================


// -------------------------------------------------------------------

class PtShape final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lattica_proto.PtShape) */ {
 public:
  inline PtShape() : PtShape(nullptr) {}
  ~PtShape() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PtShape(
      ::google::protobuf::internal::ConstantInitialized);

  inline PtShape(const PtShape& from) : PtShape(nullptr, from) {}
  inline PtShape(PtShape&& from) noexcept
      : PtShape(nullptr, std::move(from)) {}
  inline PtShape& operator=(const PtShape& from) {
    CopyFrom(from);
    return *this;
  }
  inline PtShape& operator=(PtShape&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PtShape& default_instance() {
    return *internal_default_instance();
  }
  static inline const PtShape* internal_default_instance() {
    return reinterpret_cast<const PtShape*>(
        &_PtShape_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PtShape& a, PtShape& b) { a.Swap(&b); }
  inline void Swap(PtShape* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PtShape* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PtShape* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<PtShape>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PtShape& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PtShape& from) { PtShape::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PtShape* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "lattica_proto.PtShape"; }

 protected:
  explicit PtShape(::google::protobuf::Arena* arena);
  PtShape(::google::protobuf::Arena* arena, const PtShape& from);
  PtShape(::google::protobuf::Arena* arena, PtShape&& from) noexcept
      : PtShape(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExternalShapeFieldNumber = 2,
    kInternalShapeFieldNumber = 3,
    kIntermediateShapeFieldNumber = 4,
    kInternalNFieldNumber = 1,
    kNAxisExternalFieldNumber = 5,
  };
  // repeated int32 external_shape = 2;
  int external_shape_size() const;
  private:
  int _internal_external_shape_size() const;

  public:
  void clear_external_shape() ;
  ::int32_t external_shape(int index) const;
  void set_external_shape(int index, ::int32_t value);
  void add_external_shape(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& external_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_external_shape();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_external_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_external_shape();

  public:
  // repeated int32 internal_shape = 3;
  int internal_shape_size() const;
  private:
  int _internal_internal_shape_size() const;

  public:
  void clear_internal_shape() ;
  ::int32_t internal_shape(int index) const;
  void set_internal_shape(int index, ::int32_t value);
  void add_internal_shape(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& internal_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_internal_shape();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_internal_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_internal_shape();

  public:
  // repeated int32 intermediate_shape = 4;
  int intermediate_shape_size() const;
  private:
  int _internal_intermediate_shape_size() const;

  public:
  void clear_intermediate_shape() ;
  ::int32_t intermediate_shape(int index) const;
  void set_intermediate_shape(int index, ::int32_t value);
  void add_intermediate_shape(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& intermediate_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_intermediate_shape();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_intermediate_shape() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_intermediate_shape();

  public:
  // int32 internal_n = 1;
  void clear_internal_n() ;
  ::int32_t internal_n() const;
  void set_internal_n(::int32_t value);

  private:
  ::int32_t _internal_internal_n() const;
  void _internal_set_internal_n(::int32_t value);

  public:
  // int32 n_axis_external = 5;
  void clear_n_axis_external() ;
  ::int32_t n_axis_external() const;
  void set_n_axis_external(::int32_t value);

  private:
  ::int32_t _internal_n_axis_external() const;
  void _internal_set_n_axis_external(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lattica_proto.PtShape)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_PtShape_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PtShape& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> external_shape_;
    mutable ::google::protobuf::internal::CachedSize _external_shape_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> internal_shape_;
    mutable ::google::protobuf::internal::CachedSize _internal_shape_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> intermediate_shape_;
    mutable ::google::protobuf::internal::CachedSize _intermediate_shape_cached_byte_size_;
    ::int32_t internal_n_;
    ::int32_t n_axis_external_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serialization_2fpt_5fshape_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PtShape

// int32 internal_n = 1;
inline void PtShape::clear_internal_n() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.internal_n_ = 0;
}
inline ::int32_t PtShape::internal_n() const {
  // @@protoc_insertion_point(field_get:lattica_proto.PtShape.internal_n)
  return _internal_internal_n();
}
inline void PtShape::set_internal_n(::int32_t value) {
  _internal_set_internal_n(value);
  // @@protoc_insertion_point(field_set:lattica_proto.PtShape.internal_n)
}
inline ::int32_t PtShape::_internal_internal_n() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.internal_n_;
}
inline void PtShape::_internal_set_internal_n(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.internal_n_ = value;
}

// repeated int32 external_shape = 2;
inline int PtShape::_internal_external_shape_size() const {
  return _internal_external_shape().size();
}
inline int PtShape::external_shape_size() const {
  return _internal_external_shape_size();
}
inline void PtShape::clear_external_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.external_shape_.Clear();
}
inline ::int32_t PtShape::external_shape(int index) const {
  // @@protoc_insertion_point(field_get:lattica_proto.PtShape.external_shape)
  return _internal_external_shape().Get(index);
}
inline void PtShape::set_external_shape(int index, ::int32_t value) {
  _internal_mutable_external_shape()->Set(index, value);
  // @@protoc_insertion_point(field_set:lattica_proto.PtShape.external_shape)
}
inline void PtShape::add_external_shape(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_external_shape()->Add(value);
  // @@protoc_insertion_point(field_add:lattica_proto.PtShape.external_shape)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& PtShape::external_shape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:lattica_proto.PtShape.external_shape)
  return _internal_external_shape();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::mutable_external_shape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:lattica_proto.PtShape.external_shape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_external_shape();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
PtShape::_internal_external_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.external_shape_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::_internal_mutable_external_shape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.external_shape_;
}

// repeated int32 internal_shape = 3;
inline int PtShape::_internal_internal_shape_size() const {
  return _internal_internal_shape().size();
}
inline int PtShape::internal_shape_size() const {
  return _internal_internal_shape_size();
}
inline void PtShape::clear_internal_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.internal_shape_.Clear();
}
inline ::int32_t PtShape::internal_shape(int index) const {
  // @@protoc_insertion_point(field_get:lattica_proto.PtShape.internal_shape)
  return _internal_internal_shape().Get(index);
}
inline void PtShape::set_internal_shape(int index, ::int32_t value) {
  _internal_mutable_internal_shape()->Set(index, value);
  // @@protoc_insertion_point(field_set:lattica_proto.PtShape.internal_shape)
}
inline void PtShape::add_internal_shape(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_internal_shape()->Add(value);
  // @@protoc_insertion_point(field_add:lattica_proto.PtShape.internal_shape)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& PtShape::internal_shape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:lattica_proto.PtShape.internal_shape)
  return _internal_internal_shape();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::mutable_internal_shape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:lattica_proto.PtShape.internal_shape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_internal_shape();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
PtShape::_internal_internal_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.internal_shape_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::_internal_mutable_internal_shape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.internal_shape_;
}

// repeated int32 intermediate_shape = 4;
inline int PtShape::_internal_intermediate_shape_size() const {
  return _internal_intermediate_shape().size();
}
inline int PtShape::intermediate_shape_size() const {
  return _internal_intermediate_shape_size();
}
inline void PtShape::clear_intermediate_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.intermediate_shape_.Clear();
}
inline ::int32_t PtShape::intermediate_shape(int index) const {
  // @@protoc_insertion_point(field_get:lattica_proto.PtShape.intermediate_shape)
  return _internal_intermediate_shape().Get(index);
}
inline void PtShape::set_intermediate_shape(int index, ::int32_t value) {
  _internal_mutable_intermediate_shape()->Set(index, value);
  // @@protoc_insertion_point(field_set:lattica_proto.PtShape.intermediate_shape)
}
inline void PtShape::add_intermediate_shape(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_intermediate_shape()->Add(value);
  // @@protoc_insertion_point(field_add:lattica_proto.PtShape.intermediate_shape)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& PtShape::intermediate_shape() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:lattica_proto.PtShape.intermediate_shape)
  return _internal_intermediate_shape();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::mutable_intermediate_shape()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:lattica_proto.PtShape.intermediate_shape)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_intermediate_shape();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
PtShape::_internal_intermediate_shape() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.intermediate_shape_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PtShape::_internal_mutable_intermediate_shape() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.intermediate_shape_;
}

// int32 n_axis_external = 5;
inline void PtShape::clear_n_axis_external() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_axis_external_ = 0;
}
inline ::int32_t PtShape::n_axis_external() const {
  // @@protoc_insertion_point(field_get:lattica_proto.PtShape.n_axis_external)
  return _internal_n_axis_external();
}
inline void PtShape::set_n_axis_external(::int32_t value) {
  _internal_set_n_axis_external(value);
  // @@protoc_insertion_point(field_set:lattica_proto.PtShape.n_axis_external)
}
inline ::int32_t PtShape::_internal_n_axis_external() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.n_axis_external_;
}
inline void PtShape::_internal_set_n_axis_external(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_axis_external_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_serialization_2fpt_5fshape_2eproto_2epb_2eh
