// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/ciphertexts.proto
// Protobuf C++ Version: 5.27.1

#include "ciphertexts.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace lattica_proto {

inline constexpr CKKS_Pt_Scale::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : pt_scale_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CKKS_Pt_Scale::CKKS_Pt_Scale(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CKKS_Pt_ScaleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CKKS_Pt_ScaleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CKKS_Pt_ScaleDefaultTypeInternal() {}
  union {
    CKKS_Pt_Scale _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CKKS_Pt_ScaleDefaultTypeInternal _CKKS_Pt_Scale_default_instance_;

inline constexpr Ciphertext::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        a_{nullptr},
        b_{nullptr},
        pt_shape_{nullptr},
        state_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Ciphertext::Ciphertext(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CiphertextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CiphertextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CiphertextDefaultTypeInternal() {}
  union {
    Ciphertext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CiphertextDefaultTypeInternal _Ciphertext_default_instance_;

inline constexpr RBGV_Ciphertext::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ciphertext_{nullptr},
        correction_factor_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR RBGV_Ciphertext::RBGV_Ciphertext(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RBGV_CiphertextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RBGV_CiphertextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RBGV_CiphertextDefaultTypeInternal() {}
  union {
    RBGV_Ciphertext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RBGV_CiphertextDefaultTypeInternal _RBGV_Ciphertext_default_instance_;

inline constexpr CKKS_Ciphertext::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pt_scale_{},
        ciphertext_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CKKS_Ciphertext::CKKS_Ciphertext(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CKKS_CiphertextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CKKS_CiphertextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CKKS_CiphertextDefaultTypeInternal() {}
  union {
    CKKS_Ciphertext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CKKS_CiphertextDefaultTypeInternal _CKKS_Ciphertext_default_instance_;
}  // namespace lattica_proto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_serialization_2fciphertexts_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_serialization_2fciphertexts_2eproto = nullptr;
const ::uint32_t
    TableStruct_serialization_2fciphertexts_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _impl_.a_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _impl_.b_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _impl_.pt_shape_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Ciphertext, _impl_.state_),
        0,
        1,
        2,
        3,
        PROTOBUF_FIELD_OFFSET(::lattica_proto::RBGV_Ciphertext, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::RBGV_Ciphertext, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::RBGV_Ciphertext, _impl_.ciphertext_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::RBGV_Ciphertext, _impl_.correction_factor_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Pt_Scale, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Pt_Scale, _impl_.pt_scale_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Ciphertext, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Ciphertext, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Ciphertext, _impl_.ciphertext_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::CKKS_Ciphertext, _impl_.pt_scale_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::lattica_proto::Ciphertext)},
        {16, 26, -1, sizeof(::lattica_proto::RBGV_Ciphertext)},
        {28, -1, -1, sizeof(::lattica_proto::CKKS_Pt_Scale)},
        {37, 47, -1, sizeof(::lattica_proto::CKKS_Ciphertext)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::lattica_proto::_Ciphertext_default_instance_._instance,
    &::lattica_proto::_RBGV_Ciphertext_default_instance_._instance,
    &::lattica_proto::_CKKS_Pt_Scale_default_instance_._instance,
    &::lattica_proto::_CKKS_Ciphertext_default_instance_._instance,
};
const char descriptor_table_protodef_serialization_2fciphertexts_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037serialization/ciphertexts.proto\022\rlatti"
    "ca_proto\032\033serialization/generic.proto\032\034s"
    "erialization/pt_shape.proto\032+serializati"
    "on/global_params_and_state.proto\"\272\001\n\nCip"
    "hertext\022&\n\001a\030\001 \001(\0132\033.lattica_proto.Tenso"
    "rHolder\022&\n\001b\030\002 \001(\0132\033.lattica_proto.Tenso"
    "rHolder\022(\n\010pt_shape\030\003 \001(\0132\026.lattica_prot"
    "o.PtShape\022(\n\005state\030\004 \001(\0132\024.lattica_proto"
    ".StateH\000\210\001\001B\010\n\006_state\"[\n\017RBGV_Ciphertext"
    "\022-\n\nciphertext\030\001 \001(\0132\031.lattica_proto.Cip"
    "hertext\022\031\n\021correction_factor\030\002 \001(\003\"!\n\rCK"
    "KS_Pt_Scale\022\020\n\010pt_scale\030\001 \003(\001\"R\n\017CKKS_Ci"
    "phertext\022-\n\nciphertext\030\001 \001(\0132\031.lattica_p"
    "roto.Ciphertext\022\020\n\010pt_scale\030\002 \003(\001b\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_serialization_2fciphertexts_2eproto_deps[3] =
    {
        &::descriptor_table_serialization_2fgeneric_2eproto,
        &::descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
        &::descriptor_table_serialization_2fpt_5fshape_2eproto,
};
static ::absl::once_flag descriptor_table_serialization_2fciphertexts_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_serialization_2fciphertexts_2eproto = {
    false,
    false,
    561,
    descriptor_table_protodef_serialization_2fciphertexts_2eproto,
    "serialization/ciphertexts.proto",
    &descriptor_table_serialization_2fciphertexts_2eproto_once,
    descriptor_table_serialization_2fciphertexts_2eproto_deps,
    3,
    4,
    schemas,
    file_default_instances,
    TableStruct_serialization_2fciphertexts_2eproto::offsets,
    file_level_enum_descriptors_serialization_2fciphertexts_2eproto,
    file_level_service_descriptors_serialization_2fciphertexts_2eproto,
};
namespace lattica_proto {
// ===================================================================

class Ciphertext::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Ciphertext>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_._has_bits_);
};

void Ciphertext::clear_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.a_ != nullptr) _impl_.a_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Ciphertext::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.b_ != nullptr) _impl_.b_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void Ciphertext::clear_pt_shape() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pt_shape_ != nullptr) _impl_.pt_shape_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Ciphertext::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.state_ != nullptr) _impl_.state_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
Ciphertext::Ciphertext(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::Ciphertext& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Ciphertext::Ciphertext(
    ::google::protobuf::Arena* arena,
    const Ciphertext& from)
    : ::google::protobuf::Message(arena) {
  Ciphertext* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.a_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.a_)
                        : nullptr;
  _impl_.b_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.b_)
                        : nullptr;
  _impl_.pt_shape_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::PtShape>(
                              arena, *from._impl_.pt_shape_)
                        : nullptr;
  _impl_.state_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::State>(
                              arena, *from._impl_.state_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:lattica_proto.Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Ciphertext::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, a_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, a_) +
               sizeof(Impl_::state_));
}
Ciphertext::~Ciphertext() {
  // @@protoc_insertion_point(destructor:lattica_proto.Ciphertext)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Ciphertext::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.a_;
  delete _impl_.b_;
  delete _impl_.pt_shape_;
  delete _impl_.state_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Ciphertext::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_._cached_size_),
              false,
          },
          &Ciphertext::MergeImpl,
          &Ciphertext::kDescriptorMethods,
          &descriptor_table_serialization_2fciphertexts_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 4, 0, 2> Ciphertext::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Ciphertext_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::Ciphertext>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .lattica_proto.State state = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.state_)}},
    // .lattica_proto.TensorHolder a = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.a_)}},
    // .lattica_proto.TensorHolder b = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.b_)}},
    // .lattica_proto.PtShape pt_shape = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.pt_shape_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .lattica_proto.TensorHolder a = 1;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.a_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.TensorHolder b = 2;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.b_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.PtShape pt_shape = 3;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.pt_shape_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .lattica_proto.State state = 4;
    {PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.state_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::PtShape>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::State>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Ciphertext::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.Ciphertext)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.a_ != nullptr);
      _impl_.a_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.b_ != nullptr);
      _impl_.b_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.pt_shape_ != nullptr);
      _impl_.pt_shape_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.state_ != nullptr);
      _impl_.state_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Ciphertext::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.Ciphertext)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.TensorHolder a = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.a_, _impl_.a_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.TensorHolder b = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.b_, _impl_.b_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.PtShape pt_shape = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.pt_shape_, _impl_.pt_shape_->GetCachedSize(), target, stream);
  }

  // optional .lattica_proto.State state = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.state_, _impl_.state_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.Ciphertext)
  return target;
}

::size_t Ciphertext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.Ciphertext)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // .lattica_proto.TensorHolder a = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.a_);
    }

    // .lattica_proto.TensorHolder b = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.b_);
    }

    // .lattica_proto.PtShape pt_shape = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pt_shape_);
    }

    // optional .lattica_proto.State state = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.state_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Ciphertext::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Ciphertext*>(&to_msg);
  auto& from = static_cast<const Ciphertext&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.Ciphertext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.a_ != nullptr);
      if (_this->_impl_.a_ == nullptr) {
        _this->_impl_.a_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.a_);
      } else {
        _this->_impl_.a_->MergeFrom(*from._impl_.a_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.b_ != nullptr);
      if (_this->_impl_.b_ == nullptr) {
        _this->_impl_.b_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.b_);
      } else {
        _this->_impl_.b_->MergeFrom(*from._impl_.b_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.pt_shape_ != nullptr);
      if (_this->_impl_.pt_shape_ == nullptr) {
        _this->_impl_.pt_shape_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::PtShape>(arena, *from._impl_.pt_shape_);
      } else {
        _this->_impl_.pt_shape_->MergeFrom(*from._impl_.pt_shape_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.state_ != nullptr);
      if (_this->_impl_.state_ == nullptr) {
        _this->_impl_.state_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::State>(arena, *from._impl_.state_);
      } else {
        _this->_impl_.state_->MergeFrom(*from._impl_.state_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Ciphertext::CopyFrom(const Ciphertext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.Ciphertext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Ciphertext::InternalSwap(Ciphertext* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.state_)
      + sizeof(Ciphertext::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(Ciphertext, _impl_.a_)>(
          reinterpret_cast<char*>(&_impl_.a_),
          reinterpret_cast<char*>(&other->_impl_.a_));
}

::google::protobuf::Metadata Ciphertext::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RBGV_Ciphertext::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RBGV_Ciphertext>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_._has_bits_);
};

RBGV_Ciphertext::RBGV_Ciphertext(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.RBGV_Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE RBGV_Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::RBGV_Ciphertext& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

RBGV_Ciphertext::RBGV_Ciphertext(
    ::google::protobuf::Arena* arena,
    const RBGV_Ciphertext& from)
    : ::google::protobuf::Message(arena) {
  RBGV_Ciphertext* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ciphertext_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::Ciphertext>(
                              arena, *from._impl_.ciphertext_)
                        : nullptr;
  _impl_.correction_factor_ = from._impl_.correction_factor_;

  // @@protoc_insertion_point(copy_constructor:lattica_proto.RBGV_Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE RBGV_Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RBGV_Ciphertext::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ciphertext_),
           0,
           offsetof(Impl_, correction_factor_) -
               offsetof(Impl_, ciphertext_) +
               sizeof(Impl_::correction_factor_));
}
RBGV_Ciphertext::~RBGV_Ciphertext() {
  // @@protoc_insertion_point(destructor:lattica_proto.RBGV_Ciphertext)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RBGV_Ciphertext::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.ciphertext_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RBGV_Ciphertext::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_._cached_size_),
              false,
          },
          &RBGV_Ciphertext::MergeImpl,
          &RBGV_Ciphertext::kDescriptorMethods,
          &descriptor_table_serialization_2fciphertexts_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> RBGV_Ciphertext::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RBGV_Ciphertext_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::RBGV_Ciphertext>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 correction_factor = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RBGV_Ciphertext, _impl_.correction_factor_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.correction_factor_)}},
    // .lattica_proto.Ciphertext ciphertext = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.ciphertext_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .lattica_proto.Ciphertext ciphertext = 1;
    {PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.ciphertext_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 correction_factor = 2;
    {PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.correction_factor_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::Ciphertext>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RBGV_Ciphertext::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.RBGV_Ciphertext)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.ciphertext_ != nullptr);
    _impl_.ciphertext_->Clear();
  }
  _impl_.correction_factor_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RBGV_Ciphertext::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.RBGV_Ciphertext)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.Ciphertext ciphertext = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.ciphertext_, _impl_.ciphertext_->GetCachedSize(), target, stream);
  }

  // int64 correction_factor = 2;
  if (this->_internal_correction_factor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_correction_factor(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.RBGV_Ciphertext)
  return target;
}

::size_t RBGV_Ciphertext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.RBGV_Ciphertext)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .lattica_proto.Ciphertext ciphertext = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.ciphertext_);
  }

  // int64 correction_factor = 2;
  if (this->_internal_correction_factor() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_correction_factor());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RBGV_Ciphertext::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RBGV_Ciphertext*>(&to_msg);
  auto& from = static_cast<const RBGV_Ciphertext&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.RBGV_Ciphertext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.ciphertext_ != nullptr);
    if (_this->_impl_.ciphertext_ == nullptr) {
      _this->_impl_.ciphertext_ =
          ::google::protobuf::Message::CopyConstruct<::lattica_proto::Ciphertext>(arena, *from._impl_.ciphertext_);
    } else {
      _this->_impl_.ciphertext_->MergeFrom(*from._impl_.ciphertext_);
    }
  }
  if (from._internal_correction_factor() != 0) {
    _this->_impl_.correction_factor_ = from._impl_.correction_factor_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RBGV_Ciphertext::CopyFrom(const RBGV_Ciphertext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.RBGV_Ciphertext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RBGV_Ciphertext::InternalSwap(RBGV_Ciphertext* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.correction_factor_)
      + sizeof(RBGV_Ciphertext::_impl_.correction_factor_)
      - PROTOBUF_FIELD_OFFSET(RBGV_Ciphertext, _impl_.ciphertext_)>(
          reinterpret_cast<char*>(&_impl_.ciphertext_),
          reinterpret_cast<char*>(&other->_impl_.ciphertext_));
}

::google::protobuf::Metadata RBGV_Ciphertext::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CKKS_Pt_Scale::_Internal {
 public:
};

CKKS_Pt_Scale::CKKS_Pt_Scale(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.CKKS_Pt_Scale)
}
inline PROTOBUF_NDEBUG_INLINE CKKS_Pt_Scale::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::CKKS_Pt_Scale& from_msg)
      : pt_scale_{visibility, arena, from.pt_scale_},
        _cached_size_{0} {}

CKKS_Pt_Scale::CKKS_Pt_Scale(
    ::google::protobuf::Arena* arena,
    const CKKS_Pt_Scale& from)
    : ::google::protobuf::Message(arena) {
  CKKS_Pt_Scale* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lattica_proto.CKKS_Pt_Scale)
}
inline PROTOBUF_NDEBUG_INLINE CKKS_Pt_Scale::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : pt_scale_{visibility, arena},
        _cached_size_{0} {}

inline void CKKS_Pt_Scale::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CKKS_Pt_Scale::~CKKS_Pt_Scale() {
  // @@protoc_insertion_point(destructor:lattica_proto.CKKS_Pt_Scale)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CKKS_Pt_Scale::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CKKS_Pt_Scale::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CKKS_Pt_Scale, _impl_._cached_size_),
              false,
          },
          &CKKS_Pt_Scale::MergeImpl,
          &CKKS_Pt_Scale::kDescriptorMethods,
          &descriptor_table_serialization_2fciphertexts_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CKKS_Pt_Scale::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CKKS_Pt_Scale_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::CKKS_Pt_Scale>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated double pt_scale = 1;
    {::_pbi::TcParser::FastF64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CKKS_Pt_Scale, _impl_.pt_scale_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated double pt_scale = 1;
    {PROTOBUF_FIELD_OFFSET(CKKS_Pt_Scale, _impl_.pt_scale_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CKKS_Pt_Scale::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.CKKS_Pt_Scale)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pt_scale_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CKKS_Pt_Scale::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.CKKS_Pt_Scale)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated double pt_scale = 1;
  if (this->_internal_pt_scale_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_pt_scale(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.CKKS_Pt_Scale)
  return target;
}

::size_t CKKS_Pt_Scale::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.CKKS_Pt_Scale)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated double pt_scale = 1;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_pt_scale_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CKKS_Pt_Scale::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CKKS_Pt_Scale*>(&to_msg);
  auto& from = static_cast<const CKKS_Pt_Scale&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.CKKS_Pt_Scale)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pt_scale()->MergeFrom(from._internal_pt_scale());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CKKS_Pt_Scale::CopyFrom(const CKKS_Pt_Scale& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.CKKS_Pt_Scale)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CKKS_Pt_Scale::InternalSwap(CKKS_Pt_Scale* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.pt_scale_.InternalSwap(&other->_impl_.pt_scale_);
}

::google::protobuf::Metadata CKKS_Pt_Scale::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CKKS_Ciphertext::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CKKS_Ciphertext>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_._has_bits_);
};

CKKS_Ciphertext::CKKS_Ciphertext(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.CKKS_Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE CKKS_Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::CKKS_Ciphertext& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pt_scale_{visibility, arena, from.pt_scale_} {}

CKKS_Ciphertext::CKKS_Ciphertext(
    ::google::protobuf::Arena* arena,
    const CKKS_Ciphertext& from)
    : ::google::protobuf::Message(arena) {
  CKKS_Ciphertext* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ciphertext_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::Ciphertext>(
                              arena, *from._impl_.ciphertext_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:lattica_proto.CKKS_Ciphertext)
}
inline PROTOBUF_NDEBUG_INLINE CKKS_Ciphertext::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pt_scale_{visibility, arena} {}

inline void CKKS_Ciphertext::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ciphertext_ = {};
}
CKKS_Ciphertext::~CKKS_Ciphertext() {
  // @@protoc_insertion_point(destructor:lattica_proto.CKKS_Ciphertext)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CKKS_Ciphertext::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.ciphertext_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CKKS_Ciphertext::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_._cached_size_),
              false,
          },
          &CKKS_Ciphertext::MergeImpl,
          &CKKS_Ciphertext::kDescriptorMethods,
          &descriptor_table_serialization_2fciphertexts_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> CKKS_Ciphertext::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CKKS_Ciphertext_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::CKKS_Ciphertext>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated double pt_scale = 2;
    {::_pbi::TcParser::FastF64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_.pt_scale_)}},
    // .lattica_proto.Ciphertext ciphertext = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_.ciphertext_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .lattica_proto.Ciphertext ciphertext = 1;
    {PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_.ciphertext_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated double pt_scale = 2;
    {PROTOBUF_FIELD_OFFSET(CKKS_Ciphertext, _impl_.pt_scale_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::Ciphertext>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CKKS_Ciphertext::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.CKKS_Ciphertext)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pt_scale_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.ciphertext_ != nullptr);
    _impl_.ciphertext_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CKKS_Ciphertext::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.CKKS_Ciphertext)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.Ciphertext ciphertext = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.ciphertext_, _impl_.ciphertext_->GetCachedSize(), target, stream);
  }

  // repeated double pt_scale = 2;
  if (this->_internal_pt_scale_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_pt_scale(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.CKKS_Ciphertext)
  return target;
}

::size_t CKKS_Ciphertext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.CKKS_Ciphertext)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated double pt_scale = 2;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_pt_scale_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // .lattica_proto.Ciphertext ciphertext = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.ciphertext_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CKKS_Ciphertext::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CKKS_Ciphertext*>(&to_msg);
  auto& from = static_cast<const CKKS_Ciphertext&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.CKKS_Ciphertext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pt_scale()->MergeFrom(from._internal_pt_scale());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.ciphertext_ != nullptr);
    if (_this->_impl_.ciphertext_ == nullptr) {
      _this->_impl_.ciphertext_ =
          ::google::protobuf::Message::CopyConstruct<::lattica_proto::Ciphertext>(arena, *from._impl_.ciphertext_);
    } else {
      _this->_impl_.ciphertext_->MergeFrom(*from._impl_.ciphertext_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CKKS_Ciphertext::CopyFrom(const CKKS_Ciphertext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.CKKS_Ciphertext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CKKS_Ciphertext::InternalSwap(CKKS_Ciphertext* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pt_scale_.InternalSwap(&other->_impl_.pt_scale_);
  swap(_impl_.ciphertext_, other->_impl_.ciphertext_);
}

::google::protobuf::Metadata CKKS_Ciphertext::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_serialization_2fciphertexts_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
