// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/global_params_and_state.proto
// Protobuf C++ Version: 5.27.1

#include "global_params_and_state.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace lattica_proto {

inline constexpr GParams::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        g_vec_{nullptr},
        g_exp_{0},
        g_base_bits_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GParams::GParams(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GParamsDefaultTypeInternal() {}
  union {
    GParams _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GParamsDefaultTypeInternal _GParams_default_instance_;

inline constexpr State::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mod_state_{nullptr},
        crt_state_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR State::State(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateDefaultTypeInternal() {}
  union {
    State _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateDefaultTypeInternal _State_default_instance_;

inline constexpr Params::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        g_params_{nullptr},
        pt_g_params_{nullptr},
        crt_params_{nullptr},
        pt_pack_params_{nullptr},
        pt_mod_state_{nullptr},
        pt_pack_state_{nullptr},
        n_range_{nullptr},
        perms_base_crt_{nullptr},
        xi_{nullptr},
        n_{0},
        logn_{0},
        err_std_{0},
        sk_std_{0},
        pt_scale_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Params::Params(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamsDefaultTypeInternal() {}
  union {
    Params _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamsDefaultTypeInternal _Params_default_instance_;
}  // namespace lattica_proto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_serialization_2fglobal_5fparams_5fand_5fstate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_serialization_2fglobal_5fparams_5fand_5fstate_2eproto = nullptr;
const ::uint32_t
    TableStruct_serialization_2fglobal_5fparams_5fand_5fstate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::lattica_proto::State, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::State, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::State, _impl_.mod_state_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::State, _impl_.crt_state_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::lattica_proto::GParams, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::GParams, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::GParams, _impl_.g_exp_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::GParams, _impl_.g_base_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::GParams, _impl_.g_vec_),
        ~0u,
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.n_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.logn_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.err_std_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.sk_std_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.pt_scale_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.g_params_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.pt_g_params_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.crt_params_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.pt_pack_params_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.pt_mod_state_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.pt_pack_state_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.n_range_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.perms_base_crt_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::Params, _impl_.xi_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::lattica_proto::State)},
        {12, 23, -1, sizeof(::lattica_proto::GParams)},
        {26, 48, -1, sizeof(::lattica_proto::Params)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::lattica_proto::_State_default_instance_._instance,
    &::lattica_proto::_GParams_default_instance_._instance,
    &::lattica_proto::_Params_default_instance_._instance,
};
const char descriptor_table_protodef_serialization_2fglobal_5fparams_5fand_5fstate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n+serialization/global_params_and_state."
    "proto\022\rlattica_proto\032\033serialization/gene"
    "ric.proto\032%serialization/slot_permutatio"
    "ns.proto\032(serialization/mod_params_and_s"
    "tate.proto\032(serialization/crt_params_and"
    "_state.proto\"_\n\005State\022*\n\tmod_state\030\001 \001(\013"
    "2\027.lattica_proto.ModState\022*\n\tcrt_state\030\002"
    " \001(\0132\027.lattica_proto.CrtState\"Y\n\007GParams"
    "\022\r\n\005g_exp\030\001 \001(\005\022\023\n\013g_base_bits\030\002 \001(\005\022*\n\005"
    "g_vec\030\003 \001(\0132\033.lattica_proto.TensorHolder"
    "\"\364\003\n\006Params\022\t\n\001n\030\001 \001(\005\022\014\n\004logn\030\002 \001(\005\022\017\n\007"
    "err_std\030\003 \001(\005\022\016\n\006sk_std\030\004 \001(\005\022\020\n\010pt_scal"
    "e\030\005 \001(\003\022(\n\010g_params\030\006 \001(\0132\026.lattica_prot"
    "o.GParams\022+\n\013pt_g_params\030\007 \001(\0132\026.lattica"
    "_proto.GParams\022,\n\ncrt_params\030\010 \001(\0132\030.lat"
    "tica_proto.CrtParams\0220\n\016pt_pack_params\030\t"
    " \001(\0132\030.lattica_proto.CrtParams\022-\n\014pt_mod"
    "_state\030\n \001(\0132\027.lattica_proto.ModState\022.\n"
    "\rpt_pack_state\030\013 \001(\0132\027.lattica_proto.Crt"
    "State\022,\n\007n_range\030\014 \001(\0132\033.lattica_proto.T"
    "ensorHolder\0226\n\016perms_base_crt\030\r \001(\0132\036.la"
    "ttica_proto.CrtPermutations\022\"\n\002xi\030\016 \001(\0132"
    "\026.lattica_proto.Complexb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto_deps[4] =
    {
        &::descriptor_table_serialization_2fcrt_5fparams_5fand_5fstate_2eproto,
        &::descriptor_table_serialization_2fgeneric_2eproto,
        &::descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto,
        &::descriptor_table_serialization_2fslot_5fpermutations_2eproto,
};
static ::absl::once_flag descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto = {
    false,
    false,
    911,
    descriptor_table_protodef_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
    "serialization/global_params_and_state.proto",
    &descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto_once,
    descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto_deps,
    4,
    3,
    schemas,
    file_default_instances,
    TableStruct_serialization_2fglobal_5fparams_5fand_5fstate_2eproto::offsets,
    file_level_enum_descriptors_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
    file_level_service_descriptors_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
};
namespace lattica_proto {
// ===================================================================

class State::_Internal {
 public:
  using HasBits =
      decltype(std::declval<State>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(State, _impl_._has_bits_);
};

void State::clear_mod_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.mod_state_ != nullptr) _impl_.mod_state_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void State::clear_crt_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.crt_state_ != nullptr) _impl_.crt_state_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
State::State(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.State)
}
inline PROTOBUF_NDEBUG_INLINE State::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::State& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

State::State(
    ::google::protobuf::Arena* arena,
    const State& from)
    : ::google::protobuf::Message(arena) {
  State* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.mod_state_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::ModState>(
                              arena, *from._impl_.mod_state_)
                        : nullptr;
  _impl_.crt_state_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtState>(
                              arena, *from._impl_.crt_state_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:lattica_proto.State)
}
inline PROTOBUF_NDEBUG_INLINE State::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void State::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mod_state_),
           0,
           offsetof(Impl_, crt_state_) -
               offsetof(Impl_, mod_state_) +
               sizeof(Impl_::crt_state_));
}
State::~State() {
  // @@protoc_insertion_point(destructor:lattica_proto.State)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void State::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.mod_state_;
  delete _impl_.crt_state_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
State::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(State, _impl_._cached_size_),
              false,
          },
          &State::MergeImpl,
          &State::kDescriptorMethods,
          &descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> State::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(State, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_State_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::State>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lattica_proto.CrtState crt_state = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(State, _impl_.crt_state_)}},
    // .lattica_proto.ModState mod_state = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(State, _impl_.mod_state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .lattica_proto.ModState mod_state = 1;
    {PROTOBUF_FIELD_OFFSET(State, _impl_.mod_state_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.CrtState crt_state = 2;
    {PROTOBUF_FIELD_OFFSET(State, _impl_.crt_state_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::ModState>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::CrtState>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void State::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.State)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.mod_state_ != nullptr);
      _impl_.mod_state_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.crt_state_ != nullptr);
      _impl_.crt_state_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* State::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.State)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.ModState mod_state = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.mod_state_, _impl_.mod_state_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.CrtState crt_state = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.crt_state_, _impl_.crt_state_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.State)
  return target;
}

::size_t State::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.State)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .lattica_proto.ModState mod_state = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.mod_state_);
    }

    // .lattica_proto.CrtState crt_state = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.crt_state_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void State::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<State*>(&to_msg);
  auto& from = static_cast<const State&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.State)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.mod_state_ != nullptr);
      if (_this->_impl_.mod_state_ == nullptr) {
        _this->_impl_.mod_state_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::ModState>(arena, *from._impl_.mod_state_);
      } else {
        _this->_impl_.mod_state_->MergeFrom(*from._impl_.mod_state_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.crt_state_ != nullptr);
      if (_this->_impl_.crt_state_ == nullptr) {
        _this->_impl_.crt_state_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtState>(arena, *from._impl_.crt_state_);
      } else {
        _this->_impl_.crt_state_->MergeFrom(*from._impl_.crt_state_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void State::CopyFrom(const State& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.State)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void State::InternalSwap(State* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(State, _impl_.crt_state_)
      + sizeof(State::_impl_.crt_state_)
      - PROTOBUF_FIELD_OFFSET(State, _impl_.mod_state_)>(
          reinterpret_cast<char*>(&_impl_.mod_state_),
          reinterpret_cast<char*>(&other->_impl_.mod_state_));
}

::google::protobuf::Metadata State::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GParams::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GParams>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GParams, _impl_._has_bits_);
};

void GParams::clear_g_vec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.g_vec_ != nullptr) _impl_.g_vec_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
GParams::GParams(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.GParams)
}
inline PROTOBUF_NDEBUG_INLINE GParams::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::GParams& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GParams::GParams(
    ::google::protobuf::Arena* arena,
    const GParams& from)
    : ::google::protobuf::Message(arena) {
  GParams* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.g_vec_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.g_vec_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, g_exp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, g_exp_),
           offsetof(Impl_, g_base_bits_) -
               offsetof(Impl_, g_exp_) +
               sizeof(Impl_::g_base_bits_));

  // @@protoc_insertion_point(copy_constructor:lattica_proto.GParams)
}
inline PROTOBUF_NDEBUG_INLINE GParams::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GParams::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, g_vec_),
           0,
           offsetof(Impl_, g_base_bits_) -
               offsetof(Impl_, g_vec_) +
               sizeof(Impl_::g_base_bits_));
}
GParams::~GParams() {
  // @@protoc_insertion_point(destructor:lattica_proto.GParams)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GParams::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.g_vec_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GParams::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GParams, _impl_._cached_size_),
              false,
          },
          &GParams::MergeImpl,
          &GParams::kDescriptorMethods,
          &descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> GParams::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GParams, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GParams_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::GParams>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 g_exp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GParams, _impl_.g_exp_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_exp_)}},
    // int32 g_base_bits = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GParams, _impl_.g_base_bits_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_base_bits_)}},
    // .lattica_proto.TensorHolder g_vec = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_vec_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 g_exp = 1;
    {PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_exp_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 g_base_bits = 2;
    {PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_base_bits_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .lattica_proto.TensorHolder g_vec = 3;
    {PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_vec_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GParams::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.GParams)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.g_vec_ != nullptr);
    _impl_.g_vec_->Clear();
  }
  ::memset(&_impl_.g_exp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.g_base_bits_) -
      reinterpret_cast<char*>(&_impl_.g_exp_)) + sizeof(_impl_.g_base_bits_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GParams::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.GParams)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 g_exp = 1;
  if (this->_internal_g_exp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_g_exp(), target);
  }

  // int32 g_base_bits = 2;
  if (this->_internal_g_base_bits() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_g_base_bits(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.TensorHolder g_vec = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.g_vec_, _impl_.g_vec_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.GParams)
  return target;
}

::size_t GParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.GParams)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .lattica_proto.TensorHolder g_vec = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.g_vec_);
  }

  // int32 g_exp = 1;
  if (this->_internal_g_exp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_g_exp());
  }

  // int32 g_base_bits = 2;
  if (this->_internal_g_base_bits() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_g_base_bits());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GParams::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GParams*>(&to_msg);
  auto& from = static_cast<const GParams&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.GParams)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.g_vec_ != nullptr);
    if (_this->_impl_.g_vec_ == nullptr) {
      _this->_impl_.g_vec_ =
          ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.g_vec_);
    } else {
      _this->_impl_.g_vec_->MergeFrom(*from._impl_.g_vec_);
    }
  }
  if (from._internal_g_exp() != 0) {
    _this->_impl_.g_exp_ = from._impl_.g_exp_;
  }
  if (from._internal_g_base_bits() != 0) {
    _this->_impl_.g_base_bits_ = from._impl_.g_base_bits_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GParams::CopyFrom(const GParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.GParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GParams::InternalSwap(GParams* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_base_bits_)
      + sizeof(GParams::_impl_.g_base_bits_)
      - PROTOBUF_FIELD_OFFSET(GParams, _impl_.g_vec_)>(
          reinterpret_cast<char*>(&_impl_.g_vec_),
          reinterpret_cast<char*>(&other->_impl_.g_vec_));
}

::google::protobuf::Metadata GParams::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Params::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Params>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Params, _impl_._has_bits_);
};

void Params::clear_crt_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.crt_params_ != nullptr) _impl_.crt_params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Params::clear_pt_pack_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pt_pack_params_ != nullptr) _impl_.pt_pack_params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void Params::clear_pt_mod_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pt_mod_state_ != nullptr) _impl_.pt_mod_state_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
void Params::clear_pt_pack_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pt_pack_state_ != nullptr) _impl_.pt_pack_state_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
void Params::clear_n_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.n_range_ != nullptr) _impl_.n_range_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
void Params::clear_perms_base_crt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.perms_base_crt_ != nullptr) _impl_.perms_base_crt_->Clear();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
void Params::clear_xi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.xi_ != nullptr) _impl_.xi_->Clear();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
Params::Params(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.Params)
}
inline PROTOBUF_NDEBUG_INLINE Params::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::Params& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Params::Params(
    ::google::protobuf::Arena* arena,
    const Params& from)
    : ::google::protobuf::Message(arena) {
  Params* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.g_params_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::GParams>(
                              arena, *from._impl_.g_params_)
                        : nullptr;
  _impl_.pt_g_params_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::GParams>(
                              arena, *from._impl_.pt_g_params_)
                        : nullptr;
  _impl_.crt_params_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtParams>(
                              arena, *from._impl_.crt_params_)
                        : nullptr;
  _impl_.pt_pack_params_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtParams>(
                              arena, *from._impl_.pt_pack_params_)
                        : nullptr;
  _impl_.pt_mod_state_ = (cached_has_bits & 0x00000010u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::ModState>(
                              arena, *from._impl_.pt_mod_state_)
                        : nullptr;
  _impl_.pt_pack_state_ = (cached_has_bits & 0x00000020u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtState>(
                              arena, *from._impl_.pt_pack_state_)
                        : nullptr;
  _impl_.n_range_ = (cached_has_bits & 0x00000040u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.n_range_)
                        : nullptr;
  _impl_.perms_base_crt_ = (cached_has_bits & 0x00000080u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtPermutations>(
                              arena, *from._impl_.perms_base_crt_)
                        : nullptr;
  _impl_.xi_ = (cached_has_bits & 0x00000100u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::Complex>(
                              arena, *from._impl_.xi_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, n_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, n_),
           offsetof(Impl_, pt_scale_) -
               offsetof(Impl_, n_) +
               sizeof(Impl_::pt_scale_));

  // @@protoc_insertion_point(copy_constructor:lattica_proto.Params)
}
inline PROTOBUF_NDEBUG_INLINE Params::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Params::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, g_params_),
           0,
           offsetof(Impl_, pt_scale_) -
               offsetof(Impl_, g_params_) +
               sizeof(Impl_::pt_scale_));
}
Params::~Params() {
  // @@protoc_insertion_point(destructor:lattica_proto.Params)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Params::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.g_params_;
  delete _impl_.pt_g_params_;
  delete _impl_.crt_params_;
  delete _impl_.pt_pack_params_;
  delete _impl_.pt_mod_state_;
  delete _impl_.pt_pack_state_;
  delete _impl_.n_range_;
  delete _impl_.perms_base_crt_;
  delete _impl_.xi_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Params::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Params, _impl_._cached_size_),
              false,
          },
          &Params::MergeImpl,
          &Params::kDescriptorMethods,
          &descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 14, 9, 0, 2> Params::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Params, _impl_._has_bits_),
    0, // no _extensions_
    14, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950912,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    9,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Params_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::Params>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 n = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Params, _impl_.n_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.n_)}},
    // int32 logn = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Params, _impl_.logn_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.logn_)}},
    // int32 err_std = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Params, _impl_.err_std_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.err_std_)}},
    // int32 sk_std = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Params, _impl_.sk_std_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.sk_std_)}},
    // int64 pt_scale = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Params, _impl_.pt_scale_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_scale_)}},
    // .lattica_proto.GParams g_params = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(Params, _impl_.g_params_)}},
    // .lattica_proto.GParams pt_g_params = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 1, 1, PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_g_params_)}},
    // .lattica_proto.CrtParams crt_params = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 2, 2, PROTOBUF_FIELD_OFFSET(Params, _impl_.crt_params_)}},
    // .lattica_proto.CrtParams pt_pack_params = 9;
    {::_pbi::TcParser::FastMtS1,
     {74, 3, 3, PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_pack_params_)}},
    // .lattica_proto.ModState pt_mod_state = 10;
    {::_pbi::TcParser::FastMtS1,
     {82, 4, 4, PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_mod_state_)}},
    // .lattica_proto.CrtState pt_pack_state = 11;
    {::_pbi::TcParser::FastMtS1,
     {90, 5, 5, PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_pack_state_)}},
    // .lattica_proto.TensorHolder n_range = 12;
    {::_pbi::TcParser::FastMtS1,
     {98, 6, 6, PROTOBUF_FIELD_OFFSET(Params, _impl_.n_range_)}},
    // .lattica_proto.CrtPermutations perms_base_crt = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 7, 7, PROTOBUF_FIELD_OFFSET(Params, _impl_.perms_base_crt_)}},
    // .lattica_proto.Complex xi = 14;
    {::_pbi::TcParser::FastMtS1,
     {114, 8, 8, PROTOBUF_FIELD_OFFSET(Params, _impl_.xi_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 n = 1;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.n_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 logn = 2;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.logn_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 err_std = 3;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.err_std_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 sk_std = 4;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.sk_std_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 pt_scale = 5;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_scale_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .lattica_proto.GParams g_params = 6;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.g_params_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.GParams pt_g_params = 7;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_g_params_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.CrtParams crt_params = 8;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.crt_params_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.CrtParams pt_pack_params = 9;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_pack_params_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.ModState pt_mod_state = 10;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_mod_state_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.CrtState pt_pack_state = 11;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_pack_state_), _Internal::kHasBitsOffset + 5, 5,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.TensorHolder n_range = 12;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.n_range_), _Internal::kHasBitsOffset + 6, 6,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.CrtPermutations perms_base_crt = 13;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.perms_base_crt_), _Internal::kHasBitsOffset + 7, 7,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.Complex xi = 14;
    {PROTOBUF_FIELD_OFFSET(Params, _impl_.xi_), _Internal::kHasBitsOffset + 8, 8,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::GParams>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::GParams>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::CrtParams>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::CrtParams>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::ModState>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::CrtState>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::CrtPermutations>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::Complex>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Params::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.Params)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.g_params_ != nullptr);
      _impl_.g_params_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.pt_g_params_ != nullptr);
      _impl_.pt_g_params_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.crt_params_ != nullptr);
      _impl_.crt_params_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.pt_pack_params_ != nullptr);
      _impl_.pt_pack_params_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(_impl_.pt_mod_state_ != nullptr);
      _impl_.pt_mod_state_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(_impl_.pt_pack_state_ != nullptr);
      _impl_.pt_pack_state_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      ABSL_DCHECK(_impl_.n_range_ != nullptr);
      _impl_.n_range_->Clear();
    }
    if (cached_has_bits & 0x00000080u) {
      ABSL_DCHECK(_impl_.perms_base_crt_ != nullptr);
      _impl_.perms_base_crt_->Clear();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    ABSL_DCHECK(_impl_.xi_ != nullptr);
    _impl_.xi_->Clear();
  }
  ::memset(&_impl_.n_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.pt_scale_) -
      reinterpret_cast<char*>(&_impl_.n_)) + sizeof(_impl_.pt_scale_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Params::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.Params)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 n = 1;
  if (this->_internal_n() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_n(), target);
  }

  // int32 logn = 2;
  if (this->_internal_logn() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_logn(), target);
  }

  // int32 err_std = 3;
  if (this->_internal_err_std() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_err_std(), target);
  }

  // int32 sk_std = 4;
  if (this->_internal_sk_std() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_sk_std(), target);
  }

  // int64 pt_scale = 5;
  if (this->_internal_pt_scale() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<5>(
            stream, this->_internal_pt_scale(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.GParams g_params = 6;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *_impl_.g_params_, _impl_.g_params_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.GParams pt_g_params = 7;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *_impl_.pt_g_params_, _impl_.pt_g_params_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.CrtParams crt_params = 8;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *_impl_.crt_params_, _impl_.crt_params_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.CrtParams pt_pack_params = 9;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *_impl_.pt_pack_params_, _impl_.pt_pack_params_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.ModState pt_mod_state = 10;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, *_impl_.pt_mod_state_, _impl_.pt_mod_state_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.CrtState pt_pack_state = 11;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        11, *_impl_.pt_pack_state_, _impl_.pt_pack_state_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.TensorHolder n_range = 12;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        12, *_impl_.n_range_, _impl_.n_range_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.CrtPermutations perms_base_crt = 13;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        13, *_impl_.perms_base_crt_, _impl_.perms_base_crt_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.Complex xi = 14;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        14, *_impl_.xi_, _impl_.xi_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.Params)
  return target;
}

::size_t Params::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.Params)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // .lattica_proto.GParams g_params = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.g_params_);
    }

    // .lattica_proto.GParams pt_g_params = 7;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pt_g_params_);
    }

    // .lattica_proto.CrtParams crt_params = 8;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.crt_params_);
    }

    // .lattica_proto.CrtParams pt_pack_params = 9;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pt_pack_params_);
    }

    // .lattica_proto.ModState pt_mod_state = 10;
    if (cached_has_bits & 0x00000010u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pt_mod_state_);
    }

    // .lattica_proto.CrtState pt_pack_state = 11;
    if (cached_has_bits & 0x00000020u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.pt_pack_state_);
    }

    // .lattica_proto.TensorHolder n_range = 12;
    if (cached_has_bits & 0x00000040u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.n_range_);
    }

    // .lattica_proto.CrtPermutations perms_base_crt = 13;
    if (cached_has_bits & 0x00000080u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.perms_base_crt_);
    }

  }
  // .lattica_proto.Complex xi = 14;
  if (cached_has_bits & 0x00000100u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.xi_);
  }

  // int32 n = 1;
  if (this->_internal_n() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_n());
  }

  // int32 logn = 2;
  if (this->_internal_logn() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_logn());
  }

  // int32 err_std = 3;
  if (this->_internal_err_std() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_err_std());
  }

  // int32 sk_std = 4;
  if (this->_internal_sk_std() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_sk_std());
  }

  // int64 pt_scale = 5;
  if (this->_internal_pt_scale() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_pt_scale());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Params::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Params*>(&to_msg);
  auto& from = static_cast<const Params&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.Params)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.g_params_ != nullptr);
      if (_this->_impl_.g_params_ == nullptr) {
        _this->_impl_.g_params_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::GParams>(arena, *from._impl_.g_params_);
      } else {
        _this->_impl_.g_params_->MergeFrom(*from._impl_.g_params_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.pt_g_params_ != nullptr);
      if (_this->_impl_.pt_g_params_ == nullptr) {
        _this->_impl_.pt_g_params_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::GParams>(arena, *from._impl_.pt_g_params_);
      } else {
        _this->_impl_.pt_g_params_->MergeFrom(*from._impl_.pt_g_params_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.crt_params_ != nullptr);
      if (_this->_impl_.crt_params_ == nullptr) {
        _this->_impl_.crt_params_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtParams>(arena, *from._impl_.crt_params_);
      } else {
        _this->_impl_.crt_params_->MergeFrom(*from._impl_.crt_params_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.pt_pack_params_ != nullptr);
      if (_this->_impl_.pt_pack_params_ == nullptr) {
        _this->_impl_.pt_pack_params_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtParams>(arena, *from._impl_.pt_pack_params_);
      } else {
        _this->_impl_.pt_pack_params_->MergeFrom(*from._impl_.pt_pack_params_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      ABSL_DCHECK(from._impl_.pt_mod_state_ != nullptr);
      if (_this->_impl_.pt_mod_state_ == nullptr) {
        _this->_impl_.pt_mod_state_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::ModState>(arena, *from._impl_.pt_mod_state_);
      } else {
        _this->_impl_.pt_mod_state_->MergeFrom(*from._impl_.pt_mod_state_);
      }
    }
    if (cached_has_bits & 0x00000020u) {
      ABSL_DCHECK(from._impl_.pt_pack_state_ != nullptr);
      if (_this->_impl_.pt_pack_state_ == nullptr) {
        _this->_impl_.pt_pack_state_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtState>(arena, *from._impl_.pt_pack_state_);
      } else {
        _this->_impl_.pt_pack_state_->MergeFrom(*from._impl_.pt_pack_state_);
      }
    }
    if (cached_has_bits & 0x00000040u) {
      ABSL_DCHECK(from._impl_.n_range_ != nullptr);
      if (_this->_impl_.n_range_ == nullptr) {
        _this->_impl_.n_range_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.n_range_);
      } else {
        _this->_impl_.n_range_->MergeFrom(*from._impl_.n_range_);
      }
    }
    if (cached_has_bits & 0x00000080u) {
      ABSL_DCHECK(from._impl_.perms_base_crt_ != nullptr);
      if (_this->_impl_.perms_base_crt_ == nullptr) {
        _this->_impl_.perms_base_crt_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::CrtPermutations>(arena, *from._impl_.perms_base_crt_);
      } else {
        _this->_impl_.perms_base_crt_->MergeFrom(*from._impl_.perms_base_crt_);
      }
    }
  }
  if (cached_has_bits & 0x00000100u) {
    ABSL_DCHECK(from._impl_.xi_ != nullptr);
    if (_this->_impl_.xi_ == nullptr) {
      _this->_impl_.xi_ =
          ::google::protobuf::Message::CopyConstruct<::lattica_proto::Complex>(arena, *from._impl_.xi_);
    } else {
      _this->_impl_.xi_->MergeFrom(*from._impl_.xi_);
    }
  }
  if (from._internal_n() != 0) {
    _this->_impl_.n_ = from._impl_.n_;
  }
  if (from._internal_logn() != 0) {
    _this->_impl_.logn_ = from._impl_.logn_;
  }
  if (from._internal_err_std() != 0) {
    _this->_impl_.err_std_ = from._impl_.err_std_;
  }
  if (from._internal_sk_std() != 0) {
    _this->_impl_.sk_std_ = from._impl_.sk_std_;
  }
  if (from._internal_pt_scale() != 0) {
    _this->_impl_.pt_scale_ = from._impl_.pt_scale_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Params::CopyFrom(const Params& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.Params)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Params::InternalSwap(Params* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Params, _impl_.pt_scale_)
      + sizeof(Params::_impl_.pt_scale_)
      - PROTOBUF_FIELD_OFFSET(Params, _impl_.g_params_)>(
          reinterpret_cast<char*>(&_impl_.g_params_),
          reinterpret_cast<char*>(&other->_impl_.g_params_));
}

::google::protobuf::Metadata Params::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_serialization_2fglobal_5fparams_5fand_5fstate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
