// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serialization/mod_params_and_state.proto
// Protobuf C++ Version: 5.27.1

#include "mod_params_and_state.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace lattica_proto {

inline constexpr ModState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        active_reconstruction_terms_{},
        active_q_{nullptr},
        active_q_list_{nullptr},
        active_rows_{nullptr},
        active_cols_{nullptr},
        active_len_q_list_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModState::ModState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ModStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModStateDefaultTypeInternal() {}
  union {
    ModState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModStateDefaultTypeInternal _ModState_default_instance_;
}  // namespace lattica_proto
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_serialization_2fmod_5fparams_5fand_5fstate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_serialization_2fmod_5fparams_5fand_5fstate_2eproto = nullptr;
const ::uint32_t
    TableStruct_serialization_2fmod_5fparams_5fand_5fstate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_q_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_len_q_list_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_q_list_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_rows_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_cols_),
        PROTOBUF_FIELD_OFFSET(::lattica_proto::ModState, _impl_.active_reconstruction_terms_),
        0,
        ~0u,
        1,
        2,
        3,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::lattica_proto::ModState)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::lattica_proto::_ModState_default_instance_._instance,
};
const char descriptor_table_protodef_serialization_2fmod_5fparams_5fand_5fstate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n(serialization/mod_params_and_state.pro"
    "to\022\rlattica_proto\032\033serialization/generic"
    ".proto\"\242\002\n\010ModState\022\'\n\010active_q\030\001 \001(\0132\025."
    "lattica_proto.BigInt\022\031\n\021active_len_q_lis"
    "t\030\002 \001(\005\0222\n\ractive_q_list\030\003 \001(\0132\033.lattica"
    "_proto.TensorHolder\0220\n\013active_rows\030\004 \001(\013"
    "2\033.lattica_proto.TensorHolder\0220\n\013active_"
    "cols\030\005 \001(\0132\033.lattica_proto.TensorHolder\022"
    ":\n\033active_reconstruction_terms\030\006 \003(\0132\025.l"
    "attica_proto.BigIntb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto_deps[1] =
    {
        &::descriptor_table_serialization_2fgeneric_2eproto,
};
static ::absl::once_flag descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto = {
    false,
    false,
    387,
    descriptor_table_protodef_serialization_2fmod_5fparams_5fand_5fstate_2eproto,
    "serialization/mod_params_and_state.proto",
    &descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto_once,
    descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_serialization_2fmod_5fparams_5fand_5fstate_2eproto::offsets,
    file_level_enum_descriptors_serialization_2fmod_5fparams_5fand_5fstate_2eproto,
    file_level_service_descriptors_serialization_2fmod_5fparams_5fand_5fstate_2eproto,
};
namespace lattica_proto {
// ===================================================================

class ModState::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ModState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ModState, _impl_._has_bits_);
};

void ModState::clear_active_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_q_ != nullptr) _impl_.active_q_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void ModState::clear_active_q_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_q_list_ != nullptr) _impl_.active_q_list_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void ModState::clear_active_rows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_rows_ != nullptr) _impl_.active_rows_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void ModState::clear_active_cols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_cols_ != nullptr) _impl_.active_cols_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void ModState::clear_active_reconstruction_terms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_reconstruction_terms_.Clear();
}
ModState::ModState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lattica_proto.ModState)
}
inline PROTOBUF_NDEBUG_INLINE ModState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lattica_proto::ModState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        active_reconstruction_terms_{visibility, arena, from.active_reconstruction_terms_} {}

ModState::ModState(
    ::google::protobuf::Arena* arena,
    const ModState& from)
    : ::google::protobuf::Message(arena) {
  ModState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.active_q_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::BigInt>(
                              arena, *from._impl_.active_q_)
                        : nullptr;
  _impl_.active_q_list_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.active_q_list_)
                        : nullptr;
  _impl_.active_rows_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.active_rows_)
                        : nullptr;
  _impl_.active_cols_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(
                              arena, *from._impl_.active_cols_)
                        : nullptr;
  _impl_.active_len_q_list_ = from._impl_.active_len_q_list_;

  // @@protoc_insertion_point(copy_constructor:lattica_proto.ModState)
}
inline PROTOBUF_NDEBUG_INLINE ModState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        active_reconstruction_terms_{visibility, arena} {}

inline void ModState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, active_q_),
           0,
           offsetof(Impl_, active_len_q_list_) -
               offsetof(Impl_, active_q_) +
               sizeof(Impl_::active_len_q_list_));
}
ModState::~ModState() {
  // @@protoc_insertion_point(destructor:lattica_proto.ModState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ModState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.active_q_;
  delete _impl_.active_q_list_;
  delete _impl_.active_rows_;
  delete _impl_.active_cols_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ModState::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ModState, _impl_._cached_size_),
              false,
          },
          &ModState::MergeImpl,
          &ModState::kDescriptorMethods,
          &descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 5, 0, 2> ModState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ModState, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ModState_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lattica_proto::ModState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .lattica_proto.BigInt active_q = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_q_)}},
    // int32 active_len_q_list = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModState, _impl_.active_len_q_list_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_len_q_list_)}},
    // .lattica_proto.TensorHolder active_q_list = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_q_list_)}},
    // .lattica_proto.TensorHolder active_rows = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 2, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_rows_)}},
    // .lattica_proto.TensorHolder active_cols = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 3, 3, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_cols_)}},
    // repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 4, PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_reconstruction_terms_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .lattica_proto.BigInt active_q = 1;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_q_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 active_len_q_list = 2;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_len_q_list_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .lattica_proto.TensorHolder active_q_list = 3;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_q_list_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.TensorHolder active_rows = 4;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_rows_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .lattica_proto.TensorHolder active_cols = 5;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_cols_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
    {PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_reconstruction_terms_), -1, 4,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lattica_proto::BigInt>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::TensorHolder>()},
    {::_pbi::TcParser::GetTable<::lattica_proto::BigInt>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ModState::Clear() {
// @@protoc_insertion_point(message_clear_start:lattica_proto.ModState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.active_reconstruction_terms_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.active_q_ != nullptr);
      _impl_.active_q_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.active_q_list_ != nullptr);
      _impl_.active_q_list_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.active_rows_ != nullptr);
      _impl_.active_rows_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.active_cols_ != nullptr);
      _impl_.active_cols_->Clear();
    }
  }
  _impl_.active_len_q_list_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ModState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lattica_proto.ModState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .lattica_proto.BigInt active_q = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.active_q_, _impl_.active_q_->GetCachedSize(), target, stream);
  }

  // int32 active_len_q_list = 2;
  if (this->_internal_active_len_q_list() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_active_len_q_list(), target);
  }

  // .lattica_proto.TensorHolder active_q_list = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.active_q_list_, _impl_.active_q_list_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.TensorHolder active_rows = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *_impl_.active_rows_, _impl_.active_rows_->GetCachedSize(), target, stream);
  }

  // .lattica_proto.TensorHolder active_cols = 5;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *_impl_.active_cols_, _impl_.active_cols_->GetCachedSize(), target, stream);
  }

  // repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_active_reconstruction_terms_size());
       i < n; i++) {
    const auto& repfield = this->_internal_active_reconstruction_terms().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            6, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lattica_proto.ModState)
  return target;
}

::size_t ModState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lattica_proto.ModState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .lattica_proto.BigInt active_reconstruction_terms = 6;
  total_size += 1UL * this->_internal_active_reconstruction_terms_size();
  for (const auto& msg : this->_internal_active_reconstruction_terms()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // .lattica_proto.BigInt active_q = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.active_q_);
    }

    // .lattica_proto.TensorHolder active_q_list = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.active_q_list_);
    }

    // .lattica_proto.TensorHolder active_rows = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.active_rows_);
    }

    // .lattica_proto.TensorHolder active_cols = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.active_cols_);
    }

  }
  // int32 active_len_q_list = 2;
  if (this->_internal_active_len_q_list() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_active_len_q_list());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ModState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModState*>(&to_msg);
  auto& from = static_cast<const ModState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lattica_proto.ModState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_active_reconstruction_terms()->MergeFrom(
      from._internal_active_reconstruction_terms());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.active_q_ != nullptr);
      if (_this->_impl_.active_q_ == nullptr) {
        _this->_impl_.active_q_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::BigInt>(arena, *from._impl_.active_q_);
      } else {
        _this->_impl_.active_q_->MergeFrom(*from._impl_.active_q_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.active_q_list_ != nullptr);
      if (_this->_impl_.active_q_list_ == nullptr) {
        _this->_impl_.active_q_list_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.active_q_list_);
      } else {
        _this->_impl_.active_q_list_->MergeFrom(*from._impl_.active_q_list_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.active_rows_ != nullptr);
      if (_this->_impl_.active_rows_ == nullptr) {
        _this->_impl_.active_rows_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.active_rows_);
      } else {
        _this->_impl_.active_rows_->MergeFrom(*from._impl_.active_rows_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.active_cols_ != nullptr);
      if (_this->_impl_.active_cols_ == nullptr) {
        _this->_impl_.active_cols_ =
            ::google::protobuf::Message::CopyConstruct<::lattica_proto::TensorHolder>(arena, *from._impl_.active_cols_);
      } else {
        _this->_impl_.active_cols_->MergeFrom(*from._impl_.active_cols_);
      }
    }
  }
  if (from._internal_active_len_q_list() != 0) {
    _this->_impl_.active_len_q_list_ = from._impl_.active_len_q_list_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModState::CopyFrom(const ModState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lattica_proto.ModState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModState::InternalSwap(ModState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.active_reconstruction_terms_.InternalSwap(&other->_impl_.active_reconstruction_terms_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_len_q_list_)
      + sizeof(ModState::_impl_.active_len_q_list_)
      - PROTOBUF_FIELD_OFFSET(ModState, _impl_.active_q_)>(
          reinterpret_cast<char*>(&_impl_.active_q_),
          reinterpret_cast<char*>(&other->_impl_.active_q_));
}

::google::protobuf::Metadata ModState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace lattica_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_serialization_2fmod_5fparams_5fand_5fstate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
